//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.WebPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClickNClaim.WebPortal.Resources.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To ensure that your are indeed a person, and to finish validating your account, please type the following captcha:.
        /// </summary>
        public static string AntiBotCaptcha {
            get {
                return ResourceManager.GetString("AntiBotCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Associate your @ViewBag.LoginProvider account..
        /// </summary>
        public static string AssociateYour {
            get {
                return ResourceManager.GetString("AssociateYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Association Form.
        /// </summary>
        public static string AssociationForm {
            get {
                return ResourceManager.GetString("AssociationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Awaiting your participation.
        /// </summary>
        public static string AwaitingYourParticipation {
            get {
                return ResourceManager.GetString("AwaitingYourParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CANCEL.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Case.
        /// </summary>
        public static string Case {
            get {
                return ResourceManager.GetString("Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Case No.
        /// </summary>
        public static string CaseNo {
            get {
                return ResourceManager.GetString("CaseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cases.
        /// </summary>
        public static string Cases {
            get {
                return ResourceManager.GetString("Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password reset.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter the email used to log in so as to receive a link to change your password..
        /// </summary>
        public static string ChangePasswordEmail {
            get {
                return ResourceManager.GetString("ChangePasswordEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change my profile picture.
        /// </summary>
        public static string ChangePic {
            get {
                return ResourceManager.GetString("ChangePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à click here to connect.
        /// </summary>
        public static string ClickHereToConnect {
            get {
                return ResourceManager.GetString("ClickHereToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please confirm your email address.
        /// </summary>
        public static string ConfirmationEmail {
            get {
                return ResourceManager.GetString("ConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a folder.
        /// </summary>
        public static string CreateFolder {
            get {
                return ResourceManager.GetString("CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create my account.
        /// </summary>
        public static string CreateMyAccount {
            get {
                return ResourceManager.GetString("CreateMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deletion of the case.
        /// </summary>
        public static string DeletionOfCase {
            get {
                return ResourceManager.GetString("DeletionOfCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date of birth.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email confirmation.
        /// </summary>
        public static string EmailConfirmation {
            get {
                return ResourceManager.GetString("EmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You will receive an email containing a link to reset your password..
        /// </summary>
        public static string EmailWillBeSentToResetPassword {
            get {
                return ResourceManager.GetString("EmailWillBeSentToResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the captcha.
        /// </summary>
        public static string EnterCaptcha {
            get {
                return ResourceManager.GetString("EnterCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter verification code.
        /// </summary>
        public static string EnterVerificationCode {
            get {
                return ResourceManager.GetString("EnterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are no external authentication services configured See &lt;a href=&quot;http://go.microsoft.com/fwlink/?LinkId=403804&quot;&gt;this article&lt;/a&gt;
        ///                for details on setting up this ASP.NET application to support logging in via external services.
        /// </summary>
        public static string ExtAuthenticationServices {
            get {
                return ResourceManager.GetString("ExtAuthenticationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The FastArbitre team thanks you for your trust..
        /// </summary>
        public static string FastArbitreThankYou {
            get {
                return ResourceManager.GetString("FastArbitreThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forgot your password ?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logging in.
        /// </summary>
        public static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login Failure.
        /// </summary>
        public static string LoginFailure {
            get {
                return ResourceManager.GetString("LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log in using your @p.Caption account.
        /// </summary>
        public static string LoginUsingAccount {
            get {
                return ResourceManager.GetString("LoginUsingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logging in via.
        /// </summary>
        public static string LoginVia {
            get {
                return ResourceManager.GetString("LoginVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My case files.
        /// </summary>
        public static string MyCaseFiles {
            get {
                return ResourceManager.GetString("MyCaseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My invites.
        /// </summary>
        public static string MyInvites {
            get {
                return ResourceManager.GetString("MyInvites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thank your for having registered with FastArbitre. To ascertain that this registration is not fraudulent, an email has been sent to confirm your address and to ensure that you are a human being..
        /// </summary>
        public static string NotifEmailWillBeSentForConf {
            get {
                return ResourceManager.GetString("NotifEmailWillBeSentForConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One last step and your account will be created.
        /// </summary>
        public static string OneLastStep {
            get {
                return ResourceManager.GetString("OneLastStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your password has been reset !.
        /// </summary>
        public static string PasswordHasBeenReset {
            get {
                return ResourceManager.GetString("PasswordHasBeenReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your password has been updated. Please.
        /// </summary>
        public static string PasswordHasBeenUpdatedPlease {
            get {
                return ResourceManager.GetString("PasswordHasBeenUpdatedPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please click on the link it contains and proceed to the last step to confirm the creation of your account..
        /// </summary>
        public static string PleaseClickOnLinkInEmail {
            get {
                return ResourceManager.GetString("PleaseClickOnLinkInEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please provide a password so that we may create your account. You will then automatically be redirected to your dispute..
        /// </summary>
        public static string ProvidePassword {
            get {
                return ResourceManager.GetString("ProvidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Registering.
        /// </summary>
        public static string Registering {
            get {
                return ResourceManager.GetString("Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reseting your password.
        /// </summary>
        public static string ResetingPassword {
            get {
                return ResourceManager.GetString("ResetingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset my password.
        /// </summary>
        public static string ResetMyPassword {
            get {
                return ResourceManager.GetString("ResetMyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send verification code.
        /// </summary>
        public static string SendVerificationCode {
            get {
                return ResourceManager.GetString("SendVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signing in.
        /// </summary>
        public static string SigningIn {
            get {
                return ResourceManager.GetString("SigningIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have authenticated yourself with &lt;strong&gt;@ViewBag.LoginProvider&lt;/strong&gt;.
        ///        Please enter a user name for the website below and click the Register button to finish
        ///        logging in..
        /// </summary>
        public static string SuccessfulAuthenticationEnterUser {
            get {
                return ResourceManager.GetString("SuccessfulAuthenticationEnterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thank you for having confirmed your email. Please @Html.ActionLink(&quot;click here to log in&quot;, &quot;Login&quot;, &quot;Account&quot;, routeValues: null, htmlAttributes: new { id = &quot;loginLink&quot; }).
        /// </summary>
        public static string ThanksForConfirmingEmail {
            get {
                return ResourceManager.GetString("ThanksForConfirmingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opposing party still unknown.
        /// </summary>
        public static string UnknownOpposingParty {
            get {
                return ResourceManager.GetString("UnknownOpposingParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown corporate id number.
        /// </summary>
        public static string UnknownTaxNumber {
            get {
                return ResourceManager.GetString("UnknownTaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We are sorry but our corporate id number search service provider does not seem to be able to find any company with the tax number provided. You can keep this number if you are sure that it is correct, or you can try again..
        /// </summary>
        public static string UnknownTaxNumberSolutionProposal {
            get {
                return ResourceManager.GetString("UnknownTaxNumberSolutionProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unsuccessful login with this service.
        /// </summary>
        public static string UnsuccessfulLogin {
            get {
                return ResourceManager.GetString("UnsuccessfulLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Via the social networks.
        /// </summary>
        public static string ViaSocialNetwork {
            get {
                return ResourceManager.GetString("ViaSocialNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are about to delete this case. If there are other parties, they will receive a notification indicating that you are leaving the case. Are you sure?.
        /// </summary>
        public static string WarningCaseDeletion {
            get {
                return ResourceManager.GetString("WarningCaseDeletion", resourceCulture);
            }
        }
    }
}
