//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.WebPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClickClaim {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClickClaim() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClickNClaim.WebPortal.Resources.ClickClaim", typeof(ClickClaim).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à applicable from 1st September 2016.
        /// </summary>
        public static string ApplicableFrom {
            get {
                return ResourceManager.GetString("ApplicableFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arbitration rules.
        /// </summary>
        public static string ArbitrationRules {
            get {
                return ResourceManager.GetString("ArbitrationRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à present arbitration agreement setting out the applicable rules for the resolution of the Dispute..
        /// </summary>
        public static string ArbitrationRulesDef {
            get {
                return ResourceManager.GetString("ArbitrationRulesDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arbitrator.
        /// </summary>
        public static string Arbitrator {
            get {
                return ResourceManager.GetString("Arbitrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à any physical person nominated by the Center to resolve a Dispute in accordance with the present Arbitration Rules..
        /// </summary>
        public static string ArbitratorDef {
            get {
                return ResourceManager.GetString("ArbitratorDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 1.	DEFINITIONS.
        /// </summary>
        public static string Art1 {
            get {
                return ResourceManager.GetString("Art1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 2.	SCOPE OF APPLICATION.
        /// </summary>
        public static string Art2 {
            get {
                return ResourceManager.GetString("Art2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;p&gt;The present general conditions of use are applicable to all the Users. The simple connection to the Website implies full acceptance of the present general conditions.&lt;/p&gt;
        ///                &lt;p&gt;When signing up on the Website, this acceptance will be confirmed by ticking the box corresponding to the following sentence : &lt;i&gt;&quot; I recognize that I have read and accepted the general conditions of service, the Arbitration Rules and the fees applicable&quot;&lt;/i&gt;. The User further acknowledges having read them in full an [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Art2Provisions {
            get {
                return ResourceManager.GetString("Art2Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 3.	OBJECT OF THE WEBSITE.
        /// </summary>
        public static string Art3 {
            get {
                return ResourceManager.GetString("Art3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;p&gt;The Website&apos;s objective is to make a Platform available to the Users for the resolution of Disputes. &lt;/p&gt;
        ///                &lt;p&gt;The Users can access freely the online space to bring their case. The Users can access freely the online space to bring their case. However, access to arbitration proceedings is a paid service.&lt;/p&gt;.
        /// </summary>
        public static string Art3Provisions {
            get {
                return ResourceManager.GetString("Art3Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 4.	ORDER - ARBITRATION.
        /// </summary>
        public static string Art4 {
            get {
                return ResourceManager.GetString("Art4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Order and arbitration proceedings are governed by the arbitration rules of the Digital Institut of Arbitration and Mediation (Institut digital d&apos;arbitrage et de médiation)..
        /// </summary>
        public static string Art4Provisions {
            get {
                return ResourceManager.GetString("Art4Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 5.	PRICE - PAYMENT.
        /// </summary>
        public static string Art5 {
            get {
                return ResourceManager.GetString("Art5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5.1.	Price.
        /// </summary>
        public static string Art5_1 {
            get {
                return ResourceManager.GetString("Art5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The prices applicable are those contained by the Tariffs on the day of the Request for Arbitration. Those prices can be modified at any moment by the Center. The prices indicated on the Website are in euros, excluding taxes..
        /// </summary>
        public static string Art5_1Provisions {
            get {
                return ResourceManager.GetString("Art5_1Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5.2.	Payment Terms.
        /// </summary>
        public static string Art5_2 {
            get {
                return ResourceManager.GetString("Art5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Party may pay by wire transfer or by credit card by means of a secured payment method provided by the banking and financial service providers used by the FastArbitre platform..
        /// </summary>
        public static string Art5_2Provisions_L1 {
            get {
                return ResourceManager.GetString("Art5_2Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à When paying using a credit card, the Center does not have access to any of the credit card details of the Party. The payment is made directly to the banking institution..
        /// </summary>
        public static string Art5_2Provisions_L2 {
            get {
                return ResourceManager.GetString("Art5_2Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5.3.	Repayment of the Fees to the Arbitrator.
        /// </summary>
        public static string Art5_3 {
            get {
                return ResourceManager.GetString("Art5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitrator mandates the Center to collect the sums owed him by the Parties and corresponding to his fees..
        /// </summary>
        public static string Art5_3Provisions_L1 {
            get {
                return ResourceManager.GetString("Art5_3Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitrator&apos;s fees will be paid to him by the Center by wire transfer, within 15 days of the publication of the Award on the Website, after deduction of the Center&apos;s fee as per the the Tariffs and under the condition that the corresponding invoice has been sent by the Arbitrator. In the event of the challenge of an Arbitrator, the fees will be paid in full to the Arbitrator publishing the Award on the Platform..
        /// </summary>
        public static string Art5_3Provisions_L2 {
            get {
                return ResourceManager.GetString("Art5_3Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5.4.	Confirmation of Payment - Billing.
        /// </summary>
        public static string Art5_4 {
            get {
                return ResourceManager.GetString("Art5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à When the Center receives payment, it commits to confirming receipt to the Claimant by email, within 24 hours at most. Within the same timeframe, the Center commits to sending to the Claimant an email containing an order summary, confirming the processing of the order and containing all the related information..
        /// </summary>
        public static string Art5_4Provisions_L1 {
            get {
                return ResourceManager.GetString("Art5_4Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Center will send or make available to the Party a bill by email after each payment. The Party expressly accepts to receive the bills by email..
        /// </summary>
        public static string Art5_4Provisions_L2 {
            get {
                return ResourceManager.GetString("Art5_4Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5.5.	Non-Payment.
        /// </summary>
        public static string Art5_5 {
            get {
                return ResourceManager.GetString("Art5_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The dates of payment convened upon may not be postponed under any pretence, even in the event of a dispute..
        /// </summary>
        public static string Art5_5Provisions_L1 {
            get {
                return ResourceManager.GetString("Art5_5Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Any unpaid sum at its due date will give rise, by right and without prior notice, to the application of late fees calculated on the basis of 3 times the French legal interest rate. The application of late fees shall in no event mean that the sums owed in principal are no longer due..
        /// </summary>
        public static string Art5_5Provisions_L2 {
            get {
                return ResourceManager.GetString("Art5_5Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Furthermore, any delay in payment will result in the billing to the defaulting Party of recovery costs amounting to 40 euros, in all the sums still owed being immediatly due whatever the due date convened beforehand, in these sums being raised by 20 % by way of a penalty clause, and in the possibility to rescind the contract unilaterally due to the Party&apos;s own fault..
        /// </summary>
        public static string Art5_5Provisions_L3 {
            get {
                return ResourceManager.GetString("Art5_5Provisions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 6.	ONLINE WORKSPACE.
        /// </summary>
        public static string Art6 {
            get {
                return ResourceManager.GetString("Art6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.1.	Creation of the Online Workspace.
        /// </summary>
        public static string Art6_1 {
            get {
                return ResourceManager.GetString("Art6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The creation of an online workspace is an essential prerequisite to any use of the Platform. To this end, the User is invited to provide certain personal information. Some of this information is deemed indispensable for the creation of the online workspace. The User&apos;s denial to provide the said information will impede the creation of the online workspace and, incidently, the use of the Platform..
        /// </summary>
        public static string Art6_1Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_1Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à When creating the online workspace, the User is asked to provide a password. This password constitutes  a guarantee of the confidentiality of the information contained by the personnal workspace. The User commits to not forwarding it or communicating it to a third party. Should the User fail to comply, the Center cannot be held liable  for any unauthorized access to the User&apos;s online workspace..
        /// </summary>
        public static string Art6_1Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_1Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The User commits to regularly verifying the information concerning him and to proceed online, from his workspace, to making the necessary updates and modifications..
        /// </summary>
        public static string Art6_1Provisions_L3 {
            get {
                return ResourceManager.GetString("Art6_1Provisions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.2.	Content of the Online Workspace.
        /// </summary>
        public static string Art6_2 {
            get {
                return ResourceManager.GetString("Art6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The online workspace allows Users to build their case, and then to participate in the arbitration proceedings on the Platform..
        /// </summary>
        public static string Art6_2Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_2Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The webpages of the workspace are freely printable by the holder of the account in question, but do not constitute evidence admissible by a court. The sole purpose of these webpages is to provide information intended to ensure an efficient administration of its orders by the User..
        /// </summary>
        public static string Art6_2Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_2Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Center commits to preserving securly all the contractual elements whose preservation is required by the law or regulation in force..
        /// </summary>
        public static string Art6_2Provisions_L3 {
            get {
                return ResourceManager.GetString("Art6_2Provisions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.3.	Deletion of the Online Workspace.
        /// </summary>
        public static string Art6_3 {
            get {
                return ResourceManager.GetString("Art6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Center reserves the right to delete any User&apos;s account that contravenes to the present general conditions, particularly when the User provides information that is incorrect, incomplete, misleading or fraudulent, and when the workspace has remained inactive for at least a year. The said deletion cannot constitute a fault by the Center or a loss for the excluded User, who will hence not be able to claim any damages..
        /// </summary>
        public static string Art6_3Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_3Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This exclusion is without prejudice to the possibility for the Center to undertake legal proceedings against the User when the facts justify them..
        /// </summary>
        public static string Art6_3Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_3Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 7.	THE CENTER&apos;S LIABILITY.
        /// </summary>
        public static string Art7 {
            get {
                return ResourceManager.GetString("Art7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7.1.	The Nature of the Center&apos;s Obligations.
        /// </summary>
        public static string Art7_1 {
            get {
                return ResourceManager.GetString("Art7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7.1.1.	Provision of Arbitration Organisation Services.
        /// </summary>
        public static string Art7_1_1 {
            get {
                return ResourceManager.GetString("Art7_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Center commits to taking the necessary care and diligence for the provision of arbitration organisation services in the sens of article 1450 of the French Code of civil procedure corresponding to the specifications of the present general conditions. The Center will not be liable for the arbitration services provided by the Arbitrators..
        /// </summary>
        public static string Art7_1_1Provisions_L1 {
            get {
                return ResourceManager.GetString("Art7_1_1Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Center is only subject to an obligation of means concerning the services covered by the present general conditions..
        /// </summary>
        public static string Art7_1_1Provisions_L2 {
            get {
                return ResourceManager.GetString("Art7_1_1Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7.1.2.	Provision of an Electronic Platform.
        /// </summary>
        public static string Art7_1_2 {
            get {
                return ResourceManager.GetString("Art7_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Under the present General conditions the Center acts as a totally neutral simple technical provider providing Users with an online electronic platform. The Center will therefore have the status of host of the data exchanged between Users via the Platform under their own responsibility..
        /// </summary>
        public static string Art7_1_2Provisions_L1 {
            get {
                return ResourceManager.GetString("Art7_1_2Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Center will therefore not be liable under criminal or civil law as a consequence of this data, unless, from the moment it has had knowledge of the illicit activity or information, it has not acted promptly to withdraw this information or blocked its access. .
        /// </summary>
        public static string Art7_1_2Provisions_L2 {
            get {
                return ResourceManager.GetString("Art7_1_2Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7.2.	Force majeure - The User&apos;s Fault.
        /// </summary>
        public static string Art7_2 {
            get {
                return ResourceManager.GetString("Art7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7.2.1.	Force majeure.
        /// </summary>
        public static string Art7_2_1 {
            get {
                return ResourceManager.GetString("Art7_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Under the present general conditions, a case of force majeure opposable to the Users is understood to be any impediment, limitation or disturbance of the Service arising from a fire, an epidemic, explosion, earthquake, variations of the bandwidth, default of the internet service provider, failure of the data networks, collapse of the installations, illicit or fraudulent use of passwords, codes or references, hacking of a security vulnerability imputable to the Website host or IT developers, flood, power cut [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Art7_2_1Provisions {
            get {
                return ResourceManager.GetString("Art7_2_1Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7.2.2.	User&apos;s Fault.
        /// </summary>
        public static string Art7_2_2 {
            get {
                return ResourceManager.GetString("Art7_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Under the present general conditions, will be considered a fault from the User&apos;s part and opposable to him any improper use of the Service, fault, negligence, omission or default from his part or from his employees, non-compliance with the advice given by the Center on its Website, any disclosure or illicit use of his password, codes and references, and filling out incorrect information and not updating this information on his online profile. Will also be considered a fault by the User, the implementation o [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Art7_2_2Provisions {
            get {
                return ResourceManager.GetString("Art7_2_2Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Center will not be liable in the event of force majeure or of the User&apos;s own fault, as defined by the present article:.
        /// </summary>
        public static string Art7_2Provisions {
            get {
                return ResourceManager.GetString("Art7_2Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7.3.	Technical Problems - Hyperlinks.
        /// </summary>
        public static string Art7_3 {
            get {
                return ResourceManager.GetString("Art7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In the event that the Website is inaccessible, due to technical problems of any nature, the User will not be able to invoque a loss and will not be able to claim damages. The unavailability, even a prolonged one and without any limitation, of one or more online services, cannot constitute a loss for the Users and cannot give way to the awarding of damages by the Center..
        /// </summary>
        public static string Art7_3Provisions_L1 {
            get {
                return ResourceManager.GetString("Art7_3Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The hyperlinks present on the Website may connect the User to other websites. The Center cannot be liable if the content of theses websites violates the existing legislation. Likewise, the Center cannot be liable if visiting one of these websites causes the Web User a prejudice..
        /// </summary>
        public static string Art7_3Provisions_L2 {
            get {
                return ResourceManager.GetString("Art7_3Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7.4.	Damages Payable by the Center.
        /// </summary>
        public static string Art7_4 {
            get {
                return ResourceManager.GetString("Art7_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Center&apos;s liabiliy is limited to the direct, personal and certain loss suffered by the User and linked to the failure at issue. The Center will not be liable for indirect  losses such as, the loss of data, commercial prejudice, loss of orders, deterioration of the brand&apos;s image, commercial disturbances and the loss of profits or clients. Likewise and within the same limitations, the level of damages payable by the Center cannot, in any event, be in excess of the price paid by the Party..
        /// </summary>
        public static string Art7_4Provisions {
            get {
                return ResourceManager.GetString("Art7_4Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 8.	GENERAL PROVISIONS.
        /// </summary>
        public static string Art8 {
            get {
                return ResourceManager.GetString("Art8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 8.1.	Applicable Law.
        /// </summary>
        public static string Art8_1 {
            get {
                return ResourceManager.GetString("Art8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French law is applicable to the present general conditions..
        /// </summary>
        public static string Art8_1Provisions {
            get {
                return ResourceManager.GetString("Art8_1Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 8.2.	Mediation.
        /// </summary>
        public static string Art8_2 {
            get {
                return ResourceManager.GetString("Art8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Any dispute arising from the present general conditions and not settled amicably between the parties will have to be brought to a prior mediation..
        /// </summary>
        public static string Art8_2Provisions {
            get {
                return ResourceManager.GetString("Art8_2Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 8.3.	Modification of the Present General Conditions.
        /// </summary>
        public static string Art8_3 {
            get {
                return ResourceManager.GetString("Art8_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The present General Conditions may be modified at any time by the Center. The General Conditions applicable to the Users are those in force on the day of their connection on the present Website, any new connection to the Online Workspace implying the acceptance of the new General Conditions if any..
        /// </summary>
        public static string Art8_3Provisions {
            get {
                return ResourceManager.GetString("Art8_3Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 8.4.	Entirety.
        /// </summary>
        public static string Art8_4 {
            get {
                return ResourceManager.GetString("Art8_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If any of the provisions of the present contract are voided in part or in full, the validity of the remaining provisions of the contract or the contract in full will not be affected and shall retain their full force and effect. In this case, the parties will, if possible, replace this voided provision by a valid provision corresponding to the spirit and the object of the Contract..
        /// </summary>
        public static string Art8_4Provisions {
            get {
                return ResourceManager.GetString("Art8_4Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 8.5.	Non-waiver.
        /// </summary>
        public static string Art8_5 {
            get {
                return ResourceManager.GetString("Art8_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The non-exercise by the Center of his rights under the present Contract cannot be in any way interpretated as a waiver to enforce these rights..
        /// </summary>
        public static string Art8_5Provisions {
            get {
                return ResourceManager.GetString("Art8_5Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 8.6.	Language of the Present General Conditions.
        /// </summary>
        public static string Art8_6 {
            get {
                return ResourceManager.GetString("Art8_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The present general conditions are offered in English..
        /// </summary>
        public static string Art8_6Provisions {
            get {
                return ResourceManager.GetString("Art8_6Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Award.
        /// </summary>
        public static string Award {
            get {
                return ResourceManager.GetString("Award", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à decision rendered by the Arbitrator so as to resolve the Dispute..
        /// </summary>
        public static string AwardDef {
            get {
                return ResourceManager.GetString("AwardDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Center.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Digital Institute of Arbitration and Mediation (Institut digital d’arbitrage et de médiation) acting as the administrator of the arbitration under article 1450 of the French Code of Civil Procedure..
        /// </summary>
        public static string CenterDef {
            get {
                return ResourceManager.GetString("CenterDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CENTER&apos;S LIABILITY.
        /// </summary>
        public static string CentersLiability {
            get {
                return ResourceManager.GetString("CentersLiability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claimant.
        /// </summary>
        public static string Claimant {
            get {
                return ResourceManager.GetString("Claimant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Party having first brought its case to the Platform..
        /// </summary>
        public static string ClaimantDef {
            get {
                return ResourceManager.GetString("ClaimantDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Costs.
        /// </summary>
        public static string Costs {
            get {
                return ResourceManager.GetString("Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à contractual provisions determining the amount of costs and fees for the resolution of the Dispute via the Platform..
        /// </summary>
        public static string CostsDef {
            get {
                return ResourceManager.GetString("CostsDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Defendant.
        /// </summary>
        public static string Defendant {
            get {
                return ResourceManager.GetString("Defendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Party disputing the case brought by the Claimant..
        /// </summary>
        public static string DefendantDef {
            get {
                return ResourceManager.GetString("DefendantDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DEFINITIONS.
        /// </summary>
        public static string Definitions {
            get {
                return ResourceManager.GetString("Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dispute.
        /// </summary>
        public static string Dispute {
            get {
                return ResourceManager.GetString("Dispute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à dispute between the Parties brought to arbitration before the Center..
        /// </summary>
        public static string DisputeDef {
            get {
                return ResourceManager.GetString("DisputeDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GCU.
        /// </summary>
        public static string GCU {
            get {
                return ResourceManager.GetString("GCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GENERAL PROVISIONS.
        /// </summary>
        public static string GeneralProvisions {
            get {
                return ResourceManager.GetString("GeneralProvisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jurisdiction.
        /// </summary>
        public static string Jurisdiction {
            get {
                return ResourceManager.GetString("Jurisdiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à legal field within which the Center organizes the resolution of the Dispute..
        /// </summary>
        public static string JurisdictionDef {
            get {
                return ResourceManager.GetString("JurisdictionDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MANAGEMENT - ARBITRATION.
        /// </summary>
        public static string ManagementArbitration {
            get {
                return ResourceManager.GetString("ManagementArbitration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ONLINE WORKSPACE.
        /// </summary>
        public static string OnlineWorkspace {
            get {
                return ResourceManager.GetString("OnlineWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Party.
        /// </summary>
        public static string Party {
            get {
                return ResourceManager.GetString("Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claimant or Defendant..
        /// </summary>
        public static string PartyDef {
            get {
                return ResourceManager.GetString("PartyDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Platform.
        /// </summary>
        public static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à virtual space of Dispute resolution made available to the Users by the Center and accessible at the URL www.fast-arbitre.com, and sub-sites, mirror sites, portals and related URL variations..
        /// </summary>
        public static string PlatformDef {
            get {
                return ResourceManager.GetString("PlatformDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PRICE - PAYMENT.
        /// </summary>
        public static string PricePayment {
            get {
                return ResourceManager.GetString("PricePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PURPOSE OF THE WEBSITE.
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Request for Arbitration.
        /// </summary>
        public static string RequestForArbitration {
            get {
                return ResourceManager.GetString("RequestForArbitration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à request sent to the Center by means of the Platform by a Party or its legal representative so as to solve the Dispute in accordance with the present Arbitration Rules..
        /// </summary>
        public static string RequestForArbitrationDef {
            get {
                return ResourceManager.GetString("RequestForArbitrationDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SCOPE OF APPLICATION.
        /// </summary>
        public static string Scope {
            get {
                return ResourceManager.GetString("Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FastArbitre Terms of Service.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à any person logging in to the Platform for the resolution of a Dispute..
        /// </summary>
        public static string UserDef {
            get {
                return ResourceManager.GetString("UserDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web user.
        /// </summary>
        public static string WebUser {
            get {
                return ResourceManager.GetString("WebUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à any person, physical or legal, of private or public law, logging in to the Website..
        /// </summary>
        public static string WebUserDef {
            get {
                return ResourceManager.GetString("WebUserDef", resourceCulture);
            }
        }
    }
}
