//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.WebPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Conflict {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Conflict() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClickNClaim.WebPortal.Resources.Conflict", typeof(Conflict).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What is your disagreement about?.
        /// </summary>
        public static string AboutDisagreement {
            get {
                return ResourceManager.GetString("AboutDisagreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What is your dispute about?.
        /// </summary>
        public static string AboutDispute {
            get {
                return ResourceManager.GetString("AboutDispute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Does your disagreement concern something else?.
        /// </summary>
        public static string AboutSmthgElse {
            get {
                return ResourceManager.GetString("AboutSmthgElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add an opposing party.
        /// </summary>
        public static string AddAnOpposingParty {
            get {
                return ResourceManager.GetString("AddAnOpposingParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add another party.
        /// </summary>
        public static string AddAnotherParty {
            get {
                return ResourceManager.GetString("AddAnotherParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a free comment.
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à add dates.
        /// </summary>
        public static string AddDates {
            get {
                return ResourceManager.GetString("AddDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a fact.
        /// </summary>
        public static string AddFact {
            get {
                return ResourceManager.GetString("AddFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AMIABLE STAGE BETWEEN THE PARTIES.
        /// </summary>
        public static string AmiableStage {
            get {
                return ResourceManager.GetString("AmiableStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can now send your case to the opposing party filled out when the file was created..
        /// </summary>
        public static string AmiableStageDescription_L1 {
            get {
                return ResourceManager.GetString("AmiableStageDescription_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The opposing party will read the file, provide his/her answers and version of the dispute..
        /// </summary>
        public static string AmiableStageDescription_L2 {
            get {
                return ResourceManager.GetString("AmiableStageDescription_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At this stage, this informal procedure between the parties can lead to an amicable solution..
        /// </summary>
        public static string AmiableStageDescription_L3 {
            get {
                return ResourceManager.GetString("AmiableStageDescription_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Otherwise, either party may request arbitration proceedings on the Fast-Arbitre.com platform..
        /// </summary>
        public static string AmiableStageDescription_L4 {
            get {
                return ResourceManager.GetString("AmiableStageDescription_L4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A document regarding the event described.
        /// </summary>
        public static string AnExhibit {
            get {
                return ResourceManager.GetString("AnExhibit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARBITRAL PHASE BETWEEN THE PARTIES.
        /// </summary>
        public static string ArbitralPhase {
            get {
                return ResourceManager.GetString("ArbitralPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FastArbitre appoints an impartial arbitrator with a recognized expertise on the legal issues raised..
        /// </summary>
        public static string ArbitralPhaseDes_L1 {
            get {
                return ResourceManager.GetString("ArbitralPhaseDes_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The designated arbitrator helps each party to complete their file in order to have all the elements necessary for him to render an informed decision..
        /// </summary>
        public static string ArbitralPhaseDes_L2 {
            get {
                return ResourceManager.GetString("ArbitralPhaseDes_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The arbitrator settles the dispute by taking an award that is binding for the parties and which can be enforced just as a judgment emanating from a state court..
        /// </summary>
        public static string ArbitralPhaseDes_L3 {
            get {
                return ResourceManager.GetString("ArbitralPhaseDes_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arbitration clause.
        /// </summary>
        public static string ArbitrationClause {
            get {
                return ResourceManager.GetString("ArbitrationClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This arbitration clause obliges the parties to resort to arbitration in the event of a dispute in order to obtain a quick resolution..
        /// </summary>
        public static string ArbitrationClauseExplanation {
            get {
                return ResourceManager.GetString("ArbitrationClauseExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are your represented by a lawyer?.
        /// </summary>
        public static string AreYouRepresentedByALawyer {
            get {
                return ResourceManager.GetString("AreYouRepresentedByALawyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A bill.
        /// </summary>
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Case No.
        /// </summary>
        public static string CaseNo {
            get {
                return ResourceManager.GetString("CaseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Challenge application.
        /// </summary>
        public static string ChallengeApplication {
            get {
                return ResourceManager.GetString("ChallengeApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Challenge his statement.
        /// </summary>
        public static string ChallengeStatement {
            get {
                return ResourceManager.GetString("ChallengeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You now have the opportunity to challenge the statement above. You do not need to take the entries in order or cite all the documents you may have to prove your case. Describe as simply as possible what points you challenge of the above, during the next phase you will have the possibility to be more specific by taking the entries one by one and by uploading all the documents your deem relevant to your case..
        /// </summary>
        public static string ChallengeStatementInstructions {
            get {
                return ResourceManager.GetString("ChallengeStatementInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose from the list.
        /// </summary>
        public static string ChooseFromList {
            get {
                return ResourceManager.GetString("ChooseFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chronology.
        /// </summary>
        public static string Chronology {
            get {
                return ResourceManager.GetString("Chronology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To add a new entry, click &quot;Add Entry&quot; below this box..
        /// </summary>
        public static string ChronologyAddNewEntry {
            get {
                return ResourceManager.GetString("ChronologyAddNewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can date and comment each of these entries and upload attachments..
        /// </summary>
        public static string ChronologyDetails {
            get {
                return ResourceManager.GetString("ChronologyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do not hesitate to create as many additional entries as you deem necessary:.
        /// </summary>
        public static string ChronologyEntries {
            get {
                return ResourceManager.GetString("ChronologyEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à For example: you first signed a contract with the opposing party (this constitutes an entry), then the opposing party failed to pay (this is another entry); you wrote to ask the opposing party to pay (this is a third entry); he answered challenging your request (this is a fourth entry) and so on....
        /// </summary>
        public static string ChronologyEx {
            get {
                return ResourceManager.GetString("ChronologyEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This will allow the arbitrator to better understand the situation..
        /// </summary>
        public static string ChronologyHelpArb {
            get {
                return ResourceManager.GetString("ChronologyHelpArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Be sure to give a chronology of the facts in the most accurate and comprehensive manner..
        /// </summary>
        public static string ChronologyInstructions {
            get {
                return ResourceManager.GetString("ChronologyInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à These may include e-mails, minutes of meetings; any element that may reinforce your case..
        /// </summary>
        public static string ChronologyMoreEntries {
            get {
                return ResourceManager.GetString("ChronologyMoreEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claims.
        /// </summary>
        public static string Claims {
            get {
                return ResourceManager.GetString("Claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You will now fill out your claims..
        /// </summary>
        public static string ClaimsInstructions_L1 {
            get {
                return ResourceManager.GetString("ClaimsInstructions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please indicate what you would claim before the arbitrator..
        /// </summary>
        public static string ClaimsInstructions_L2 {
            get {
                return ResourceManager.GetString("ClaimsInstructions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To help you, we have categorized some common claims. For example, you can claim a sum of money, the return of goods or the performance of a service. However, we may not have thought of everything. In this case, the section &quot;Other&quot; will allow you to customize your claims..
        /// </summary>
        public static string ClaimsInstructions_L3 {
            get {
                return ResourceManager.GetString("ClaimsInstructions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please try to make your claims as specific as possible and to be as comprehensive as possible. For example, when claiming a sum of money, indicate the amount and think of how to justify that amount. Generally, you will need to provide a document supporting your claim..
        /// </summary>
        public static string ClaimsInstructions_L4 {
            get {
                return ResourceManager.GetString("ClaimsInstructions_L4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à When you feel that you have thought of everything, move on to the next phase..
        /// </summary>
        public static string ClaimsInstructions_L5 {
            get {
                return ResourceManager.GetString("ClaimsInstructions_L5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By forwarding your file, we will first make sure that we are able to resolve your situation.
        ///                 We commit to responding within 24 hours. You will receive an e-mail confirming that your request was taken into account and that your request was forwarded to the third parties involved in the dispute. A registered letter with acknowledgment of receipt will also be sent to you..
        /// </summary>
        public static string ConfirmationProcessExplanation {
            get {
                return ResourceManager.GetString("ConfirmationProcessExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A contract may be constituted by:.
        /// </summary>
        public static string ConstitutionContract {
            get {
                return ResourceManager.GetString("ConstitutionContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You said that you have a contract. Please indicate below the details of this contract..
        /// </summary>
        public static string ContractInfo {
            get {
                return ResourceManager.GetString("ContractInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please indicate if the dispute arose from a contractual relationship between the parties..
        /// </summary>
        public static string ContractualDispute {
            get {
                return ResourceManager.GetString("ContractualDispute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Does your dispute involve a contract?.
        /// </summary>
        public static string ContractualDisputeQ {
            get {
                return ResourceManager.GetString("ContractualDisputeQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à He will take care of the constitution of your file. During the rest of the proceedings you will have a read-only access..
        /// </summary>
        public static string CounselWillFillOutFile {
            get {
                return ResourceManager.GetString("CounselWillFillOutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your lawyer will receive an invitation by email to connect to the FastArbitre platform..
        /// </summary>
        public static string CounselWillReceiveInvitation {
            get {
                return ResourceManager.GetString("CounselWillReceiveInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You will now formulate counterclaims in response to your adversary&apos;s claims..
        /// </summary>
        public static string CounterClaimsInstructions_L1 {
            get {
                return ResourceManager.GetString("CounterClaimsInstructions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You may yourself wish to make claims against your adversary or ask that his claims be totally or partially rejected..
        /// </summary>
        public static string CounterClaimsInstructions_L2 {
            get {
                return ResourceManager.GetString("CounterClaimsInstructions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You therefore need to list what you would ask from the arbitrator within the frame of your dispute..
        /// </summary>
        public static string CounterClaimsInstructions_L3 {
            get {
                return ResourceManager.GetString("CounterClaimsInstructions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Company/Entrepreneur.
        /// </summary>
        public static string CyEntrepreneur {
            get {
                return ResourceManager.GetString("CyEntrepreneur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Company name.
        /// </summary>
        public static string CyName {
            get {
                return ResourceManager.GetString("CyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please specify whether your are the company involved in the dispute or its legal counsel..
        /// </summary>
        public static string CyOrCounsel {
            get {
                return ResourceManager.GetString("CyOrCounsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date of the contract.
        /// </summary>
        public static string DateContract {
            get {
                return ResourceManager.GetString("DateContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indicate the date of the event.
        /// </summary>
        public static string DateEvent {
            get {
                return ResourceManager.GetString("DateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disagreement over the entry.
        /// </summary>
        public static string DisagreementOnFact {
            get {
                return ResourceManager.GetString("DisagreementOnFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disagreement(s) over:.
        /// </summary>
        public static string DisagreementOver {
            get {
                return ResourceManager.GetString("DisagreementOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dispute between individuals.
        /// </summary>
        public static string DisputeBetweenIndividuals {
            get {
                return ResourceManager.GetString("DisputeBetweenIndividuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your dispute concerns:.
        /// </summary>
        public static string DisputeConcerns {
            get {
                return ResourceManager.GetString("DisputeConcerns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dispute for .
        /// </summary>
        public static string DisputeForCy {
            get {
                return ResourceManager.GetString("DisputeForCy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timeline of the dispute.
        /// </summary>
        public static string DisputeTimeline {
            get {
                return ResourceManager.GetString("DisputeTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upload clause.
        /// </summary>
        public static string DownloadClause {
            get {
                return ResourceManager.GetString("DownloadClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please upload the document containing the arbitration clause..
        /// </summary>
        public static string DownloadDocArbClause {
            get {
                return ResourceManager.GetString("DownloadDocArbClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you also have a claim to make?.
        /// </summary>
        public static string DoYouAlsoHaveClaim {
            get {
                return ResourceManager.GetString("DoYouAlsoHaveClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you have an arbitration clause in your contract?.
        /// </summary>
        public static string DoYouHaveArbitrationClause {
            get {
                return ResourceManager.GetString("DoYouHaveArbitrationClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you have an arbitration clause in the contract between you and the other party?.
        /// </summary>
        public static string DoYouHaveArbitrationClause2 {
            get {
                return ResourceManager.GetString("DoYouHaveArbitrationClause2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you have a contract with the previously identified individuals containing an arbitration clause?.
        /// </summary>
        public static string DoYouHaveContractAndArbClause {
            get {
                return ResourceManager.GetString("DoYouHaveContractAndArbClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you have any documents or contracts justifying your position?.
        /// </summary>
        public static string DoYouHaveDocs {
            get {
                return ResourceManager.GetString("DoYouHaveDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you have exhibits, documents or contracts justifying this?.
        /// </summary>
        public static string DoYouHaveExhibits {
            get {
                return ResourceManager.GetString("DoYouHaveExhibits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An email.
        /// </summary>
        public static string EmailExchange {
            get {
                return ResourceManager.GetString("EmailExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Each email must be unique and correspond to the opposing party..
        /// </summary>
        public static string EmailWarning {
            get {
                return ResourceManager.GetString("EmailWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à end filing.
        /// </summary>
        public static string EndFiling {
            get {
                return ResourceManager.GetString("EndFiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End of filing.
        /// </summary>
        public static string EndOfFiling {
            get {
                return ResourceManager.GetString("EndOfFiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Existence of an arbitration clause.
        /// </summary>
        public static string ExistenceArbClause {
            get {
                return ResourceManager.GetString("ExistenceArbClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Explain the reason you disagree with this application.
        /// </summary>
        public static string ExplainDisagreement {
            get {
                return ResourceManager.GetString("ExplainDisagreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please explain in your own words the context and the reasons for your dispute.
        /// </summary>
        public static string ExplainInYourOwnWordsDispute {
            get {
                return ResourceManager.GetString("ExplainInYourOwnWordsDispute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Explanation of your conflict.
        /// </summary>
        public static string ExplanationOfYourConflict {
            get {
                return ResourceManager.GetString("ExplanationOfYourConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Facts and Exhibits.
        /// </summary>
        public static string FactsExhibits {
            get {
                return ResourceManager.GetString("FactsExhibits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Give the most relevant facts and their date to allow the arbitrator to fully understand what exactly happened and when..
        /// </summary>
        public static string FactsInstructions_L1 {
            get {
                return ResourceManager.GetString("FactsInstructions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The objective is to illustrate the description of the problem you want to solve and support your position..
        /// </summary>
        public static string FactsInstructions_L2 {
            get {
                return ResourceManager.GetString("FactsInstructions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title of the Entry.
        /// </summary>
        public static string FactTitle {
            get {
                return ResourceManager.GetString("FactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please give as much information as possible about the facts that led to your problem. Do not hesitate to create as many entries as you think necessary. This may include sending an e-mail whose content pleads in your favor, a document that has been sent to you or that you sent, or anything else that would lead the arbitrator to a better understanding of the situation..
        /// </summary>
        public static string FactualEntries {
            get {
                return ResourceManager.GetString("FactualEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your file is almost complete.
        /// </summary>
        public static string FileNearlyComplete {
            get {
                return ResourceManager.GetString("FileNearlyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finalize my file and forward it to the other parties.
        /// </summary>
        public static string FinalizeMyFile {
            get {
                return ResourceManager.GetString("FinalizeMyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Function.
        /// </summary>
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please give the email address of the people with whom your dispute is (1 per line).
        /// </summary>
        public static string GiveEmailOfAdversary {
            get {
                return ResourceManager.GetString("GiveEmailOfAdversary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à has written:.
        /// </summary>
        public static string HasWritten {
            get {
                return ResourceManager.GetString("HasWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have completed your case file. You can return to it, modify it and enrich it at will (access via the MY FILES option on your online profile)..
        /// </summary>
        public static string HowToGoBackToFile {
            get {
                return ResourceManager.GetString("HowToGoBackToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identification.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I disagree with.
        /// </summary>
        public static string IDisagreeWith {
            get {
                return ResourceManager.GetString("IDisagreeWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If a lawyer represents you during these proceedings, please click on yes then fill out his / her contact details in the fields which will appear below. Your lawyer will automatically receive an email enabling him to log on to FastArbitre and fill out your file. You will no longer be able to fill out your file (only your lawyer can), but you will still be able to see its progress and the elements that your lawyer and the other party will transmit..
        /// </summary>
        public static string IfLawyerReadOnly {
            get {
                return ResourceManager.GetString("IfLawyerReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you do not have a contract, please modify your answer to the question &quot;Does your dispute involve a contract?&quot;..
        /// </summary>
        public static string IfNoContract {
            get {
                return ResourceManager.GetString("IfNoContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you are represented by a lawyer in this file, click YES..
        /// </summary>
        public static string IfRepresented {
            get {
                return ResourceManager.GetString("IfRepresented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If an arbitration clause exists in your contract, please upload the document containing it.
        /// </summary>
        public static string IfYesUploadDoc {
            get {
                return ResourceManager.GetString("IfYesUploadDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Now indicate with whom you dispute is!.
        /// </summary>
        public static string IndicateAdversaries {
            get {
                return ResourceManager.GetString("IndicateAdversaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please fill out the necessary information regarding your company and yourself..
        /// </summary>
        public static string InfoRegardingCyOrYourself {
            get {
                return ResourceManager.GetString("InfoRegardingCyOrYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lawyer.
        /// </summary>
        public static string Lawyer {
            get {
                return ResourceManager.GetString("Lawyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fill out your lawyer&apos;s contact details in the corresponding fields..
        /// </summary>
        public static string LawyerContactDetails {
            get {
                return ResourceManager.GetString("LawyerContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lawyer&apos;s name.
        /// </summary>
        public static string LawyersName {
            get {
                return ResourceManager.GetString("LawyersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lawyer&apos;s surname.
        /// </summary>
        public static string LawyersSurname {
            get {
                return ResourceManager.GetString("LawyersSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Link to the video conference:.
        /// </summary>
        public static string LinkToVideoConf {
            get {
                return ResourceManager.GetString("LinkToVideoConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify the clause.
        /// </summary>
        public static string ModifyClause {
            get {
                return ResourceManager.GetString("ModifyClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify my statement.
        /// </summary>
        public static string ModifyMyStatement {
            get {
                return ResourceManager.GetString("ModifyMyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Dispute.
        /// </summary>
        public static string MyDispute {
            get {
                return ResourceManager.GetString("MyDispute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My dispute is with.
        /// </summary>
        public static string MyDisputeIsWith {
            get {
                return ResourceManager.GetString("MyDisputeIsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Disputes.
        /// </summary>
        public static string MyDisputes {
            get {
                return ResourceManager.GetString("MyDisputes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New clause:.
        /// </summary>
        public static string NewClause {
            get {
                return ResourceManager.GetString("NewClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click NO if your dispute does not relate to a contract but to a factual situation where you are opposed to a third party with whom you do not have a direct business relationship (including a competitor)..
        /// </summary>
        public static string NoContract {
            get {
                return ResourceManager.GetString("NoContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;No date saved&quot;.
        /// </summary>
        public static string NoDate {
            get {
                return ResourceManager.GetString("NoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are currently no entries for this conflict. Click Add Entry to begin describing your dispute, stage by stage..
        /// </summary>
        public static string NoFactsExist {
            get {
                return ResourceManager.GetString("NoFactsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opening date.
        /// </summary>
        public static string OpeningDate {
            get {
                return ResourceManager.GetString("OpeningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Did you attempt something else to resolve the dispute?.
        /// </summary>
        public static string OtherResolutionAttempt {
            get {
                return ResourceManager.GetString("OtherResolutionAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parties concerned.
        /// </summary>
        public static string PartiesConcerned {
            get {
                return ResourceManager.GetString("PartiesConcerned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have indicated that you are represented by a lawyer. He will be responsible for filling out the remainder of your file. When this page is confirmed, only your lawyer will be able to complete your file. Do not be afraid, you will in any case have the possibility to take knowledge of the progress of your file directly and all the elements that your lawyer or the opposing party will transmit..
        /// </summary>
        public static string PartyWarning {
            get {
                return ResourceManager.GetString("PartyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Position in the company.
        /// </summary>
        public static string PositionInCy {
            get {
                return ResourceManager.GetString("PositionInCy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Have you tried to settle your dispute?.
        /// </summary>
        public static string PriorResolutionAttempt {
            get {
                return ResourceManager.GetString("PriorResolutionAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A purchase order.
        /// </summary>
        public static string PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A quotation.
        /// </summary>
        public static string Quotation {
            get {
                return ResourceManager.GetString("Quotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à See uploaded clause.
        /// </summary>
        public static string SeeDownloadedClause {
            get {
                return ResourceManager.GetString("SeeDownloadedClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à See more.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In this list, select the items that match your case.
        /// </summary>
        public static string SelectCorresponding {
            get {
                return ResourceManager.GetString("SelectCorresponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à From this list, select the elements that correspond to your file.
        /// </summary>
        public static string SelectFromListCorrespondingElements {
            get {
                return ResourceManager.GetString("SelectFromListCorrespondingElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A signed document (electronically or not).
        /// </summary>
        public static string SignedDoc {
            get {
                return ResourceManager.GetString("SignedDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Social reason of the company.
        /// </summary>
        public static string SocialReason {
            get {
                return ResourceManager.GetString("SocialReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please indicate the date at which you believe the event took place:.
        /// </summary>
        public static string SpecifyDate {
            get {
                return ResourceManager.GetString("SpecifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please specify the reason for your disagreement on this entry:.
        /// </summary>
        public static string SpecifyDisagreement {
            get {
                return ResourceManager.GetString("SpecifyDisagreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please indicate on which exhibit your disagreement is over:.
        /// </summary>
        public static string SpecifyExhibit {
            get {
                return ResourceManager.GetString("SpecifyExhibit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statement by.
        /// </summary>
        public static string StatementBy {
            get {
                return ResourceManager.GetString("StatementBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The purpose of this statement is to allow you to describe the dispute. On this page are empty fields to describe synthetically the dispute, focusing on specific facts, in a concise and clear language. Please indicate in particular the nature of your link or relationship with the opposing party (customer, recipient, supplier, etc.)..
        /// </summary>
        public static string StatementInstructions_L1 {
            get {
                return ResourceManager.GetString("StatementInstructions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do not describe everything, just the basics. During the next phase, you will be able to substantiate your position by detailing the relevant facts and documents..
        /// </summary>
        public static string StatementInstructions_L2 {
            get {
                return ResourceManager.GetString("StatementInstructions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à When you have finished filling out your statement, proceed to the next phase..
        /// </summary>
        public static string StatementInstructions_L3 {
            get {
                return ResourceManager.GetString("StatementInstructions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Summary of my case.
        /// </summary>
        public static string SummaryOfMyCase {
            get {
                return ResourceManager.GetString("SummaryOfMyCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are about to submit your request for dispute resolution through the FastArbitre platform and we thank you for that..
        /// </summary>
        public static string ThanksForSubmission {
            get {
                return ResourceManager.GetString("ThanksForSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The date of the event described.
        /// </summary>
        public static string TheDate {
            get {
                return ResourceManager.GetString("TheDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The exhibit(s):.
        /// </summary>
        public static string TheExhibits {
            get {
                return ResourceManager.GetString("TheExhibits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The entry and its description.
        /// </summary>
        public static string TheFactAndDescription {
            get {
                return ResourceManager.GetString("TheFactAndDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The event described itself.
        /// </summary>
        public static string TheFactItself {
            get {
                return ResourceManager.GetString("TheFactItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have just given your arguments, together with the facts and documents of the dispute..
        /// </summary>
        public static string TimelineInfoInstructions_L1 {
            get {
                return ResourceManager.GetString("TimelineInfoInstructions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To better visualize them, we have automatically presented them below in the form of a timeline..
        /// </summary>
        public static string TimelineInfoInstructions_L2 {
            get {
                return ResourceManager.GetString("TimelineInfoInstructions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please read them carefully to make sure they are accurate enough..
        /// </summary>
        public static string TimelineInfoInstructions_L3 {
            get {
                return ResourceManager.GetString("TimelineInfoInstructions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you wish, you can add to them with a new fact or a free comment..
        /// </summary>
        public static string TimelineInfoInstructions_L4 {
            get {
                return ResourceManager.GetString("TimelineInfoInstructions_L4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you are satisfied with it, go to the next step..
        /// </summary>
        public static string TimelineInfoInstructions_L5 {
            get {
                return ResourceManager.GetString("TimelineInfoInstructions_L5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To get help, click the Help button at the bottom right of your screen. You will find this button at each step of your statement..
        /// </summary>
        public static string ToGetHelp {
            get {
                return ResourceManager.GetString("ToGetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upload clause.
        /// </summary>
        public static string UploadClause {
            get {
                return ResourceManager.GetString("UploadClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Video conference planned for the.
        /// </summary>
        public static string VideoConfDate {
            get {
                return ResourceManager.GetString("VideoConfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Waiting for.
        /// </summary>
        public static string WaitingFor {
            get {
                return ResourceManager.GetString("WaitingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What are the facts of the case according to you?.
        /// </summary>
        public static string WhatAreTheFacts {
            get {
                return ResourceManager.GetString("WhatAreTheFacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What contract do you have with your contracting partner?.
        /// </summary>
        public static string WhatContract {
            get {
                return ResourceManager.GetString("WhatContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What is the name of the lawyer who represents you?.
        /// </summary>
        public static string WhatIsTheNameOfTheLawyer {
            get {
                return ResourceManager.GetString("WhatIsTheNameOfTheLawyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What is your name?.
        /// </summary>
        public static string WhatIsYourName {
            get {
                return ResourceManager.GetString("WhatIsYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The arbitration clause is available for download below..
        /// </summary>
        public static string WhereToDownloadClause {
            get {
                return ResourceManager.GetString("WhereToDownloadClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Who do your represent?.
        /// </summary>
        public static string WhoDoYouRepresent {
            get {
                return ResourceManager.GetString("WhoDoYouRepresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Who is the opposing party?.
        /// </summary>
        public static string WhoIsOpposingParty {
            get {
                return ResourceManager.GetString("WhoIsOpposingParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (The clause will be saved when you will click to the next step).
        /// </summary>
        public static string WillBeSavedNextStep {
            get {
                return ResourceManager.GetString("WillBeSavedNextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are about to fill out a statement..
        /// </summary>
        public static string YouAreAboutToFillOutStatement {
            get {
                return ResourceManager.GetString("YouAreAboutToFillOutStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your file will be forwarded to FastArbitre. You can now continue your statement
        ///                     by describing the important events that led to your dispute, or come back to it later..
        /// </summary>
        public static string YourFileWillBeTransferredToFA {
            get {
                return ResourceManager.GetString("YourFileWillBeTransferredToFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your identity.
        /// </summary>
        public static string YourId {
            get {
                return ResourceManager.GetString("YourId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your role.
        /// </summary>
        public static string YourRole {
            get {
                return ResourceManager.GetString("YourRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You will have full access to all the information of the case, the exchanges with the opposing party and the IDAM Arbitration Institute..
        /// </summary>
        public static string YouWillHaveAccess {
            get {
                return ResourceManager.GetString("YouWillHaveAccess", resourceCulture);
            }
        }
    }
}
