//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.WebPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Rules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rules() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClickNClaim.WebPortal.Resources.Rules", typeof(Rules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arbitrator.
        /// </summary>
        public static string Arbitrator {
            get {
                return ResourceManager.GetString("Arbitrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à any physical person nominated by the Center to resolve a Dispute in accordance with the present Arbitration Rules..
        /// </summary>
        public static string ArbitratorDef {
            get {
                return ResourceManager.GetString("ArbitratorDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Request for arbitration.
        /// </summary>
        public static string ArbRequest {
            get {
                return ResourceManager.GetString("ArbRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à request sent to the Center by means of the Platform by a Party or its legal representative so as to resolve the Dispute in accordance with the present Arbitration Rules..
        /// </summary>
        public static string ArbRequestDef {
            get {
                return ResourceManager.GetString("ArbRequestDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arbitration rules.
        /// </summary>
        public static string ArbRules {
            get {
                return ResourceManager.GetString("ArbRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à present arbitration agreement setting out the applicable rules for the resolution of the Dispute..
        /// </summary>
        public static string ArbRulesDef {
            get {
                return ResourceManager.GetString("ArbRulesDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 1.	DEFINITIONS.
        /// </summary>
        public static string Art1 {
            get {
                return ResourceManager.GetString("Art1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 10.	TIME LIMITS.
        /// </summary>
        public static string Art10 {
            get {
                return ResourceManager.GetString("Art10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Award is rendered by the Arbitrator as soon as possible depending on the characteristics of the Dispute. In any case, the Award must be rendered within a maximum period of six months starting from the constitution of the arbitral tribunal. This period may be extended by the Center..
        /// </summary>
        public static string Art10Provisions_L1 {
            get {
                return ResourceManager.GetString("Art10Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Each Party and the Arbitrator shall have the right at any time to submit to the Center a reasoned request for the extension or reduction of the procedural time-limits. The Center accepts or rejects this request by a non-reasonned and non-appealable decision..
        /// </summary>
        public static string Art10Provisions_L2 {
            get {
                return ResourceManager.GetString("Art10Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 11.	CONFIDENTIALITY.
        /// </summary>
        public static string Art11 {
            get {
                return ResourceManager.GetString("Art11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The arbitration and exchanges of information via the Platform are confidential. The obligation of confidentiality weighs on any User, each guaranteeing, if necessary, the observation of this obligation by its personnel and its representatives..
        /// </summary>
        public static string Art11Provisions_L1 {
            get {
                return ResourceManager.GetString("Art11Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The obligation of confidentiality does not preclude the production of information exchanged on the Platform before the state courts. Nor does it hinder the rereading of the Award by a committee of the Center for the harmonization of Awards. Members of this committee are bound by confidentiality..
        /// </summary>
        public static string Art11Provisions_L2 {
            get {
                return ResourceManager.GetString("Art11Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Award may be published after it has been anonymized..
        /// </summary>
        public static string Art11Provisions_L3 {
            get {
                return ResourceManager.GetString("Art11Provisions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 12.	IDENTIFICATION, NOTIFICATIONS AND COMMUNICATIONS.
        /// </summary>
        public static string Art12 {
            get {
                return ResourceManager.GetString("Art12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 12.1.	Identification.
        /// </summary>
        public static string Art12_1 {
            get {
                return ResourceManager.GetString("Art12_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Each Party shall provide any identification document requested by the Center or the Arbitrator..
        /// </summary>
        public static string Art12_1Provisions {
            get {
                return ResourceManager.GetString("Art12_1Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 12.2.	Notifications and communications.
        /// </summary>
        public static string Art12_2 {
            get {
                return ResourceManager.GetString("Art12_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unless otherwise provided by the Rules, notifications and communications between Users shall be made through the Platform, with each event occurring on the Platform being notified to the Parties and the Arbitrator by e-mail..
        /// </summary>
        public static string Art12_2Provisions_L1 {
            get {
                return ResourceManager.GetString("Art12_2Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Where the Rules impose a notification by registered letter, it shall be sent to the address appearing on the public register Infogreffe and corresponding to the Siret number of the addressee on the date of the notification..
        /// </summary>
        public static string Art12_2Provisions_L2 {
            get {
                return ResourceManager.GetString("Art12_2Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 13. FINAL PROVISIONS.
        /// </summary>
        public static string Art13 {
            get {
                return ResourceManager.GetString("Art13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 13.1.	Place of Arbitration.
        /// </summary>
        public static string Art13_1 {
            get {
                return ResourceManager.GetString("Art13_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The place of Arbitration is that of the Center&apos;s corporate office..
        /// </summary>
        public static string Art13_1Provisions {
            get {
                return ResourceManager.GetString("Art13_1Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 13.2.	Law Applicable to the Arbitration.
        /// </summary>
        public static string Art13_2 {
            get {
                return ResourceManager.GetString("Art13_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The arbitration&apos;s rules of procedure are subject to French law..
        /// </summary>
        public static string Art13_2Provisions {
            get {
                return ResourceManager.GetString("Art13_2Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 13.3.	Language of the Arbitration.
        /// </summary>
        public static string Art13_3 {
            get {
                return ResourceManager.GetString("Art13_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The language of the Arbitration is English..
        /// </summary>
        public static string Art13_3Provisions {
            get {
                return ResourceManager.GetString("Art13_3Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 13.4.	Interpretation of the Arbitration Rules.
        /// </summary>
        public static string Art13_4 {
            get {
                return ResourceManager.GetString("Art13_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Any interpretation of the present Arbitration Rules is of the Center&apos;s responsibility..
        /// </summary>
        public static string Art13_4Provisions {
            get {
                return ResourceManager.GetString("Art13_4Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 2.	SCOPE OF APPLICATION.
        /// </summary>
        public static string Art2 {
            get {
                return ResourceManager.GetString("Art2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2.1.	Adhesion to the Arbitration Rules.
        /// </summary>
        public static string Art2_1 {
            get {
                return ResourceManager.GetString("Art2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitration Rules and its Costs are applicable to all the Users..
        /// </summary>
        public static string Art2_1Provisions_L1 {
            get {
                return ResourceManager.GetString("Art2_1Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Parties agree to the Rules and its Costs when they submit their Dispute to the Center or the Rules, in writing by way of an arbitration clause or an arbitration agreement. Agreeing to the Rules implies that the Parties are capable of doing so, capacity that they declare being in possession of relatively to the object of the Dispute..
        /// </summary>
        public static string Art2_1Provisions_L2 {
            get {
                return ResourceManager.GetString("Art2_1Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitrators, by accepting their mission, agree to the Rules and its Costs..
        /// </summary>
        public static string Art2_1Provisions_L3 {
            get {
                return ResourceManager.GetString("Art2_1Provisions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2.2.	Agreement to Submit to the Rules.
        /// </summary>
        public static string Art2_2 {
            get {
                return ResourceManager.GetString("Art2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Party&apos;s agreement to submit to the Rules will be confirmed by ticking the box corresponding to the following sentence : &quot;I recognize having read and accepting the general conditions of service, the arbitration rules and the applicable costs&quot;. The Users also recognize having taken full knowledge of the aforementionned and accepting them without restriction..
        /// </summary>
        public static string Art2_2Provisions_L1 {
            get {
                return ResourceManager.GetString("Art2_2Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ticking the aforementionned box shall be deemed to have the same force as the Users&apos; handwritten signature, Users recognize the legal value of the Platform&apos;s records and waive their right to challenge them in the event of a dispute..
        /// </summary>
        public static string Art2_2Provisions_L2 {
            get {
                return ResourceManager.GetString("Art2_2Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The User&apos;s agreement to submit the Dispute to the Rules will be reiterated by his entering the confidential codes on the Platform sent to him by the Center by registered letter with acknowledgement of receipt so as to participate in the arbitral proceedings..
        /// </summary>
        public static string Art2_2Provisions_L3 {
            get {
                return ResourceManager.GetString("Art2_2Provisions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitration Rules applicable to the Dispute are those published on the Website on the day of the Request for Arbitration..
        /// </summary>
        public static string Art2_2Provisions_L4 {
            get {
                return ResourceManager.GetString("Art2_2Provisions_L4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2.3.	Consequences of the Agreement to Submit the Dispute to the Rules.
        /// </summary>
        public static string Art2_3 {
            get {
                return ResourceManager.GetString("Art2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Agreement to submit the Dispute to the Rules implies agreeing to submit the Dispute to the technical proceedings entailed by the use of the Platform and acceptance of the pricing conditions contained by the Costs..
        /// </summary>
        public static string Art2_3Provisions_L1 {
            get {
                return ResourceManager.GetString("Art2_3Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The present Rules and their Costs are applicable to the resolution of the Dispute, excluding any other provisions, except if the Parties have agreed to it expressly in writing..
        /// </summary>
        public static string Art2_3Provisions_L2 {
            get {
                return ResourceManager.GetString("Art2_3Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Agreeing to the present Rules and/or the voluntary participation to the arbitral proceedings on the Platform cover any possible invalidity of the arbitration clause convened upon by the Parties on a matter where arbitration is not authorized..
        /// </summary>
        public static string Art2_3Provisions_L3 {
            get {
                return ResourceManager.GetString("Art2_3Provisions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 3.	CASE ESTABLISHMENT.
        /// </summary>
        public static string Art3 {
            get {
                return ResourceManager.GetString("Art3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3.1.	Constitution of the File by the Claimant.
        /// </summary>
        public static string Art3_1 {
            get {
                return ResourceManager.GetString("Art3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3.1.1.	Claimant&apos;s Filing of Claims.
        /// </summary>
        public static string Art3_1_1 {
            get {
                return ResourceManager.GetString("Art3_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Claimant logs in and formulates his claims in accordance with the technical configuration of the Platform on the day of his declaration..
        /// </summary>
        public static string Art3_1_1Provisions {
            get {
                return ResourceManager.GetString("Art3_1_1Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3.1.2.	Validation of the File by the Claimant.
        /// </summary>
        public static string Art3_1_2 {
            get {
                return ResourceManager.GetString("Art3_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Claimant is then asked to validate his file. His declarations are then not modifiable till the arbitral proceedings. A notification is then sent to the Defendant by email so that he may take note of the claims made by the Claimant and challenge them..
        /// </summary>
        public static string Art3_1_2Provisions {
            get {
                return ResourceManager.GetString("Art3_1_2Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3.2. Constitution of the File by the Defendant.
        /// </summary>
        public static string Art3_2 {
            get {
                return ResourceManager.GetString("Art3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3.2.1.	Challenge of the Claimant&apos;s Claims.
        /// </summary>
        public static string Art3_2_1 {
            get {
                return ResourceManager.GetString("Art3_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Defendant challenges the Claimant&apos;s claims in accordance with the technical configuration of the Platform on the day of his declaration..
        /// </summary>
        public static string Art3_2_1Provisions {
            get {
                return ResourceManager.GetString("Art3_2_1Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3.2.2.	Validation of the File of the Defendant.
        /// </summary>
        public static string Art3_2_2 {
            get {
                return ResourceManager.GetString("Art3_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Defendant is then asked to validate his file. His declarations are then not modifiable till the arbitral proceedings. A notification is then sent to the Claimant by email so that he may take note of the challenges made by the Defendant..
        /// </summary>
        public static string Art3_2_2Provisions {
            get {
                return ResourceManager.GetString("Art3_2_2Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 4.	SEIZING THE ARBITRAL TRIBUNAL.
        /// </summary>
        public static string Art4 {
            get {
                return ResourceManager.GetString("Art4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4.1.	Request for Arbitration.
        /// </summary>
        public static string Art4_1 {
            get {
                return ResourceManager.GetString("Art4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à After the Defendant has validated his file, each Party can file a Request for Arbitration via the Platform..
        /// </summary>
        public static string Art4_1Provisions_L1 {
            get {
                return ResourceManager.GetString("Art4_1Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In the event of an arbitration clause designating expressly the Center or the Arbitration Rules, the Request for Arbitration is filed by one of the Parties. Therefore, upon reception of the Request made by one of the Parties regarding the Dispute, the Center is immediatly seized. .
        /// </summary>
        public static string Art4_1Provisions_L2 {
            get {
                return ResourceManager.GetString("Art4_1Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In the absence of an arbitration clause expressly designating the Center or the Arbitration Rules, the Request for Arbitration is filed jointly by both Parties. In this event, to seize the Center, one Party has to submit the Dispute to the Center and the other Party has to agree to the submission of the Dispute..
        /// </summary>
        public static string Art4_1Provisions_L3 {
            get {
                return ResourceManager.GetString("Art4_1Provisions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4.2.	Debit Authorization of the Arbitration Fees and Costs.
        /// </summary>
        public static string Art4_2 {
            get {
                return ResourceManager.GetString("Art4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à As soon as the Center is seized, it asks both Parties to provide a debit authorization on their credit card or bank account for half of the fees and costs of the arbitration..
        /// </summary>
        public static string Art4_2Provisions_L1 {
            get {
                return ResourceManager.GetString("Art4_2Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If one of the Parties does not provide the debit authorization, the other Party may choose to allow the Center to debit on his credit card or bank account all of the arbitration fees and costs..
        /// </summary>
        public static string Art4_2Provisions_L2 {
            get {
                return ResourceManager.GetString("Art4_2Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4.3.	Confirmation of the Request for Arbitration by the Center.
        /// </summary>
        public static string Art4_3 {
            get {
                return ResourceManager.GetString("Art4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4.3.1.	Jurisdiction.
        /// </summary>
        public static string Art4_3_1 {
            get {
                return ResourceManager.GetString("Art4_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Center determines freely if the Dispute, as defined by the Request for Arbitration, falls under its Jurisdiction. It accepts or refuses the Request for Arbitration by an unreasonned decision that cannot ne appealed. In the event of a refusal of the Request for Arbitration by the Center, it will inform the Parties who will then be free to bring their Dispute before another arbitration center or a state court..
        /// </summary>
        public static string Art4_3_1Provisions {
            get {
                return ResourceManager.GetString("Art4_3_1Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4.3.2.	Debit of the Arbitration Costs and Fees.
        /// </summary>
        public static string Art4_3_2 {
            get {
                return ResourceManager.GetString("Art4_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If the Center accepts the Request for Arbitration, it proceeds to the debiting of the costs and fees of the arbitration..
        /// </summary>
        public static string Art4_3_2Provisions_L1 {
            get {
                return ResourceManager.GetString("Art4_3_2Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Where necessary, with regard to the nature and the complexity of the case submitted by the Parties, the Center will inform them that the resolution of the Dispute will require the payment of additional costs and fees compared to those mentionned in Costs. The Center will then ask each Party to pay half of the costs and fees of the arbitration. If one of the Parties does not proceed to the payment, the other Party may choose to pay all of the arbitration fees and costs..
        /// </summary>
        public static string Art4_3_2Provisions_L2 {
            get {
                return ResourceManager.GetString("Art4_3_2Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4.3.3.	Notification of the Parties of the Constitution of the Arbitral Tribunal.
        /// </summary>
        public static string Art4_3_3 {
            get {
                return ResourceManager.GetString("Art4_3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à When all the costs and fees have been payed to the Center, it will inform the Parties of the constitution of the arbitral tribunal by registered letter with  acknowledgement of receipt. This notification will contain access codes allowing the Parties to login onto the Platform so as to participate in the arbitral proceedings..
        /// </summary>
        public static string Art4_3_3Provisions {
            get {
                return ResourceManager.GetString("Art4_3_3Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4.3.4.	Reimbursement of the Sums Payed.
        /// </summary>
        public static string Art4_3_4 {
            get {
                return ResourceManager.GetString("Art4_3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Should the costs and fees have not been paid in their entirety to the Center within a month starting from the Request for Arbitration, the latter will be deemend null and void and the sums possibly paid by the Parties will be reimbursed..
        /// </summary>
        public static string Art4_3_4Provisions {
            get {
                return ResourceManager.GetString("Art4_3_4Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 5.	CONSTITUTION OF THE ARBITRAL TRIBUNAL.
        /// </summary>
        public static string Art5 {
            get {
                return ResourceManager.GetString("Art5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5.1.	Appointement of the Arbitrator by the Center.
        /// </summary>
        public static string Art5_1 {
            get {
                return ResourceManager.GetString("Art5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The arbitral tribunal is composed of a sole Arbitrator appointed by the Center as soon as the fees and costs of the arbitration have been paid in their entirety..
        /// </summary>
        public static string Art5_1Provisions {
            get {
                return ResourceManager.GetString("Art5_1Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5.2.	Arbitrator&apos;s Acceptance of the Mission.
        /// </summary>
        public static string Art5_2 {
            get {
                return ResourceManager.GetString("Art5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à As soon as he is appointed the Arbitrator must accept or refuse the mission he is entrusted with by the Center..
        /// </summary>
        public static string Art5_2Provisions_L1 {
            get {
                return ResourceManager.GetString("Art5_2Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If the Arbitrator accepts his mission, he commits to fulfilling it to its end. The Arbitrator&apos;s acceptance of his mission must contain a declaration that indicates the possible circumstances that would be of such a nature that they would affect his independence and/or his impartiality. If such circumstances are revealed by the Arbitrator, he will then be confirmed or dismissed by a decision taken by the Center after having heard the Parties on this issue..
        /// </summary>
        public static string Art5_2Provisions_L2 {
            get {
                return ResourceManager.GetString("Art5_2Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If the Arbitrator refuses his mission or is dismissed, the Center will immediately appoint a new Arbitrator..
        /// </summary>
        public static string Art5_2Provisions_L3 {
            get {
                return ResourceManager.GetString("Art5_2Provisions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The arbitral tribunal is constituted as soon as the Arbitrator accepts his mission..
        /// </summary>
        public static string Art5_2Provisions_L4 {
            get {
                return ResourceManager.GetString("Art5_2Provisions_L4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Center immediately informs the Parties of the Arbitrator&apos;s acceptance of his mission..
        /// </summary>
        public static string Art5_2Provisions_L5 {
            get {
                return ResourceManager.GetString("Art5_2Provisions_L5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 6.	ARBITRAL PROCEEDINGS.
        /// </summary>
        public static string Art6 {
            get {
                return ResourceManager.GetString("Art6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.1.	General Rules of Procedure.
        /// </summary>
        public static string Art6_1 {
            get {
                return ResourceManager.GetString("Art6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitrator is to organize the arbitral proceedings via the Platform in application with the present Rules and the technical procedures of the Platform, in the way he deems appropriate, depending on the nature of the case and taking into account the dispositions possibly set out by the Parties. The Arbitrator commits to upholding, in his management of the proceedings, the leading principles for the conduct of proceedings as set out by articles 4 to 10, 11 paragraph 1, 12 paragraphs 2 and 3, 13 to 21, 23  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Art6_1Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_1Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitrator will resort to procedural orders to solve any procedural issues or incidents, and to decide upon any request for joinder or consolidation. These procedural orders cannot be appealed..
        /// </summary>
        public static string Art6_1Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_1Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All the documents and comments exchanged via the Platform may be accessed by the Parties and the Arbitrator. All of them have the possibility to comment these documents via the Platform oraly or in writing..
        /// </summary>
        public static string Art6_1Provisions_L3 {
            get {
                return ResourceManager.GetString("Art6_1Provisions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If the Parties have reached a settlement after the file has been transmitted to the arbitral tribunal they may ask the tribunal to record their settlement in the form of an Award by consent of the Parties..
        /// </summary>
        public static string Art6_1Provisions_L4 {
            get {
                return ResourceManager.GetString("Art6_1Provisions_L4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Party who knowingly and without a legitimate cause, does not invoque in due course an irregularity before the arbitral tribunal, shall be deemed to have waived its right to invoque it..
        /// </summary>
        public static string Art6_1Provisions_L5 {
            get {
                return ResourceManager.GetString("Art6_1Provisions_L5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.2.	Unfolding of the Main Proceedings.
        /// </summary>
        public static string Art6_2 {
            get {
                return ResourceManager.GetString("Art6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.2.1.	Establishing the Facts of the Case.
        /// </summary>
        public static string Art6_2_1 {
            get {
                return ResourceManager.GetString("Art6_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Starting from the constitution of the arbitral tribunal, the Arbitrator has 14 (fourteen) days to request from the Parties all that he requires to ready the case so that he may decide upon it. Each Party must answer within the delay set out..
        /// </summary>
        public static string Art6_2_1Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_2_1Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Parties then have 7 (seven) days to complete their file, supporting freely their respective claims and challenges made during the constitution of their file..
        /// </summary>
        public static string Art6_2_1Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_2_1Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.2.2.	Draft Award.
        /// </summary>
        public static string Art6_2_2 {
            get {
                return ResourceManager.GetString("Art6_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitrator then has 7 (seven) days to render a draft Award in light of the case made by each Party..
        /// </summary>
        public static string Art6_2_2Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_2_2Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Parties then have 7 (seven) days starting from the date of the draft Award&apos;s upload by the Arbitrator to further support their respective claims and challenges..
        /// </summary>
        public static string Art6_2_2Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_2_2Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.2.3.	Award.
        /// </summary>
        public static string Art6_2_3 {
            get {
                return ResourceManager.GetString("Art6_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If the Parties fail to react within the timeframe allotted, the draft Award will be considered as final..
        /// </summary>
        public static string Art6_2_3Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_2_3Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If the Parties have reacted, the Arbitrator has 7 (seven) days after the end of the time allotted to the Parties to react to decide upon the case in light of the most recent claims and challenges made by the Parties..
        /// </summary>
        public static string Art6_2_3Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_2_3Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unless the Center has fixed a procedural timetable derogating with the provisions hereafter, the main proceedings will unfold as follows:.
        /// </summary>
        public static string Art6_2Provisions {
            get {
                return ResourceManager.GetString("Art6_2Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.3.	Incidental Proceedings.
        /// </summary>
        public static string Art6_3 {
            get {
                return ResourceManager.GetString("Art6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.3.1.	General Rules.
        /// </summary>
        public static string Art6_3_1 {
            get {
                return ResourceManager.GetString("Art6_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Parties or the Arbitrator can initiate the following incidental proceedings..
        /// </summary>
        public static string Art6_3_1Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_3_1Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If the incidental proceedings are initiated by a Party, they unfold in the same manner as the main proceedings..
        /// </summary>
        public static string Art6_3_1Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_3_1Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If the incidental proceedings are initiated by the Arbitrator, he immediately takes a draft procedural order..
        /// </summary>
        public static string Art6_3_1Provisions_L3 {
            get {
                return ResourceManager.GetString("Art6_3_1Provisions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.3.2.	Challenge of the Arbitral Tribunal&apos;s Jurisdiction.
        /// </summary>
        public static string Art6_3_2 {
            get {
                return ResourceManager.GetString("Art6_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitrator will decide upon potential challenges regarding the inexistence, invalidity or inapplicability of the arbitration agreement..
        /// </summary>
        public static string Art6_3_2Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_3_2Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To be admissible, challenges of the tribunal&apos;s jurisdiction must be made before presenting any defence on the merits or plea of non-admissibility..
        /// </summary>
        public static string Art6_3_2Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_3_2Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.3.3.	Suspension and abatement of Proceedings.
        /// </summary>
        public static string Art6_3_3 {
            get {
                return ResourceManager.GetString("Art6_3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.3.3.1.	General Rules.
        /// </summary>
        public static string Art6_3_3_1 {
            get {
                return ResourceManager.GetString("Art6_3_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An abatement or stay of the proceedings shall not put an end to the arbitral tribunal&apos;s mandate..
        /// </summary>
        public static string Art6_3_3_1Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_3_3_1Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The arbitral tribunal may ask the Parties to report any steps taken towards resuming the proceedings or putting an end to the cause of the abatement or stay. In the event that the Parties fail to act, the tribunal may terminate the proceedings..
        /// </summary>
        public static string Art6_3_3_1Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_3_3_1Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proceedings resume their course at the stage that they were before the abatement or stay when the cause for this abatement or stay has ceased to exist..
        /// </summary>
        public static string Art6_3_3_1Provisions_L3 {
            get {
                return ResourceManager.GetString("Art6_3_3_1Provisions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.3.3.2.	Decision Deferring.
        /// </summary>
        public static string Art6_3_3_2 {
            get {
                return ResourceManager.GetString("Art6_3_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The arbitral tribunal may, if need be, defer its decision. This will suspend the course of the proceedings for the time or till the occurrence of the event it refers to..
        /// </summary>
        public static string Art6_3_3_2Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_3_3_2Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The period of time for the arbitration starts to run again when the arbitral tribunal is informed of the occurrence of the said event by the most diligent Party..
        /// </summary>
        public static string Art6_3_3_2Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_3_3_2Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The arbitral tribunal may, in light of the circumstances, revoque its decision to defer or shorten the time limit allotted..
        /// </summary>
        public static string Art6_3_3_2Provisions_L3 {
            get {
                return ResourceManager.GetString("Art6_3_3_2Provisions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.3.3.3.	Death, Impediment, Abstention, Resignation, Challenge, Removal.
        /// </summary>
        public static string Art6_3_3_3 {
            get {
                return ResourceManager.GetString("Art6_3_3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In the event of the death, impediment, abstention, resignation, challenge or removal of the Arbitrator, proceedings are stayed till the Arbitrator nominated as a replacement accepts his mission..
        /// </summary>
        public static string Art6_3_3_3Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_3_3_3Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This new Arbitrator is nominated by the Center. However, if a difficulty arises, the Center may seize the competent judicial authority by way of a petition so that he may proceed to replacing the Arbitrator by an order against which no recourse is available..
        /// </summary>
        public static string Art6_3_3_3Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_3_3_3Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.3.4.	Conservatory and Interim Measures.
        /// </summary>
        public static string Art6_3_4 {
            get {
                return ResourceManager.GetString("Art6_3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The arbitral tribunal may order upon the Parties any conservatory or provisional measures that it deems appropriate, set conditions for such measures and, if necessary, attach penalties to such order. However, only courts may order conservatory attachments and judicial security. .
        /// </summary>
        public static string Art6_3_4Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_3_4Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The arbitral tribunal has the power to amend or add to any provisional or conservatory measure that it has granted..
        /// </summary>
        public static string Art6_3_4Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_3_4Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.3.5.	Investigative Measures.
        /// </summary>
        public static string Art6_3_5 {
            get {
                return ResourceManager.GetString("Art6_3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.3.5.1.	General Rules.
        /// </summary>
        public static string Art6_3_5_1 {
            get {
                return ResourceManager.GetString("Art6_3_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitrator need not apply the provisions of the French Code of civil procedure on investigative measures..
        /// </summary>
        public static string Art6_3_5_1Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_3_5_1Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitrator may, in particular, order any investigative measure at the request of a Party or ex officio, without first informing the Parties, provided that the facts on which his final decision is based may have been debatted upon on the Platform before a final decision is taken..
        /// </summary>
        public static string Art6_3_5_1Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_3_5_1Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.3.5.2.	Findings of Fact.
        /// </summary>
        public static string Art6_3_5_2 {
            get {
                return ResourceManager.GetString("Art6_3_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitrator may take any steps concerning findings of fact, in particular on the Internet..
        /// </summary>
        public static string Art6_3_5_2Provisions {
            get {
                return ResourceManager.GetString("Art6_3_5_2Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.3.5.3.	Testimonies.
        /// </summary>
        public static string Art6_3_5_3 {
            get {
                return ResourceManager.GetString("Art6_3_5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitrator may hear the Parties by means of a communication process allowing for an adversarial debate. He determines the issues under discussion, as well as the time allotted to the Parties to respond to them..
        /// </summary>
        public static string Art6_3_5_3Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_3_5_3Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitrator may hear witnesses, experts or any other person whose hearing is requested by a Party or decided by him..
        /// </summary>
        public static string Art6_3_5_3Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_3_5_3Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.3.5.4.	Claim of Forgery and Verification of Handwriting.
        /// </summary>
        public static string Art6_3_5_4 {
            get {
                return ResourceManager.GetString("Art6_3_5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The copies of the exhibits produced by a Party are deemed to be sincere, unless the other Party initiates an incidental claim of forgery or verification of handwriting..
        /// </summary>
        public static string Art6_3_5_4Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_3_5_4Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitrator shall have the power to decide upon the incidental claims of forgery or verifications of handwriting. He may order any measure that may verify the sincerity of the contested exhibit..
        /// </summary>
        public static string Art6_3_5_4Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_3_5_4Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.3.5.5.	Expert Reports.
        /// </summary>
        public static string Art6_3_5_5 {
            get {
                return ResourceManager.GetString("Art6_3_5_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If he considers it necessary, the Arbitrator may appoint one or more experts..
        /// </summary>
        public static string Art6_3_5_5Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_3_5_5Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The final expert report will be drawn up as follows:.
        /// </summary>
        public static string Art6_3_5_5Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_3_5_5Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The procedural order nominating the expert precisely determines his mission and the time allotted to complete his mission..
        /// </summary>
        public static string Art6_3_5_5Provisions_L3 {
            get {
                return ResourceManager.GetString("Art6_3_5_5Provisions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The expert must produce a draft expert report within the time allotted by the Arbitrator..
        /// </summary>
        public static string Art6_3_5_5Provisions_L4 {
            get {
                return ResourceManager.GetString("Art6_3_5_5Provisions_L4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Parties have 7 (seven) clear days to make any comment on the draft expert report..
        /// </summary>
        public static string Art6_3_5_5Provisions_L5 {
            get {
                return ResourceManager.GetString("Art6_3_5_5Provisions_L5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In the absence of any objection within this period, the draft shall constitute the final expert report. If not, the expert may amend his report in light of the comments submitted by the Parties..
        /// </summary>
        public static string Art6_3_5_5Provisions_L6 {
            get {
                return ResourceManager.GetString("Art6_3_5_5Provisions_L6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Any difficulty in the unfolding of the expert&apos;s mission, not settled by the expert and the Parties, shall be referred to the Arbitrator..
        /// </summary>
        public static string Art6_3_5_5Provisions_L7 {
            get {
                return ResourceManager.GetString("Art6_3_5_5Provisions_L7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.3.5.6.	Production and Communication of Exhibits.
        /// </summary>
        public static string Art6_3_5_6 {
            get {
                return ResourceManager.GetString("Art6_3_5_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If a Party possesses evidence relevant to the outcome of the Dispute, the arbitral tribunal may notify the Party through the Platform for the disclosure or production of such evidence. In the event of an inaction by the Party, the Arbitrator may order the communication or production, by means of a reasoned procedural order, in accordance with the procedures he determines and, if necessary, attach penalties to such order..
        /// </summary>
        public static string Art6_3_5_6Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_3_5_6Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à When a Party or the Arbitrator wishes that an investigative measure be taken against a third party, the procedure set out by the present article shall be followed..
        /// </summary>
        public static string Art6_3_5_6Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_3_5_6Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If the contemplated investigative measure requires that the third party be called to the proceedings regarding the investigative measure, the procedure provided for at article 1469 of the French Code of Civil Procedure shall be followed..
        /// </summary>
        public static string Art6_3_5_6Provisions_L3 {
            get {
                return ResourceManager.GetString("Art6_3_5_6Provisions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If the investigative measure does not require that the thrid party be called to the proceedings regarding the investigative measure, the procedure shall be as follows:.
        /// </summary>
        public static string Art6_3_5_6Provisions_L4 {
            get {
                return ResourceManager.GetString("Art6_3_5_6Provisions_L4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitrator initiates a debate via the Platform, in order to gather each Party&apos;s arguments in fact and in law regarding the measure of instruction contemplated..
        /// </summary>
        public static string Art6_3_5_6Provisions_L5 {
            get {
                return ResourceManager.GetString("Art6_3_5_6Provisions_L5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitrator shall forward these arguments to the lawyer of his choice, whom the parties mandate for the purpose of filing a joint petition on their behalf before the president of the competent court hearing the application for interim measures..
        /// </summary>
        public static string Art6_3_5_6Provisions_L6 {
            get {
                return ResourceManager.GetString("Art6_3_5_6Provisions_L6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The judge hearing the case shall rule on the merits of the request of investigative measures in light of the factual and legal arguments of each Party set out in their joint petition. The Parties agree to bind the judge deciding upon his jurisdiction to hear the request for investigative measures and the admissibility of the request for the production of an exhibit in accordance with article 57-1 of the French Code of Civil Procedure..
        /// </summary>
        public static string Art6_3_5_6Provisions_L7 {
            get {
                return ResourceManager.GetString("Art6_3_5_6Provisions_L7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The parties hereafter waive any right to appeal against the decision to intervene ordering or refusing the contemplated investigative measure..
        /// </summary>
        public static string Art6_3_5_6Provisions_L8 {
            get {
                return ResourceManager.GetString("Art6_3_5_6Provisions_L8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6.4.	Challenge of Arbitrator.
        /// </summary>
        public static string Art6_4 {
            get {
                return ResourceManager.GetString("Art6_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Party who intends to challenge an Arbitrator shall immediately and within seven (7) days of the occurrence of the cause for the challenge or of its disclosure, send a reasoned request to the Center. After establishing the facts in an adversarial manner, the Center decides on this request by a decision which is not justified and non-appealable..
        /// </summary>
        public static string Art6_4Provisions_L1 {
            get {
                return ResourceManager.GetString("Art6_4Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The arbitral proceedings shall be stayed during the challenge proceedings..
        /// </summary>
        public static string Art6_4Provisions_L2 {
            get {
                return ResourceManager.GetString("Art6_4Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Once the Award has been submitted to the Center, the challenge of the Arbitrator is not admissible..
        /// </summary>
        public static string Art6_4Provisions_L3 {
            get {
                return ResourceManager.GetString("Art6_4Provisions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 7.	ARBITRAL AWARD.
        /// </summary>
        public static string Art7 {
            get {
                return ResourceManager.GetString("Art7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7.1.	Contents of the Award.
        /// </summary>
        public static string Art7_1 {
            get {
                return ResourceManager.GetString("Art7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Award settles the Dispute submitted by the Parties to the Arbitrator via the Platform. The Awards must be reasoned and succinctly set forth the Parties&apos; respective claims and arguments..
        /// </summary>
        public static string Art7_1Provisions_L1 {
            get {
                return ResourceManager.GetString("Art7_1Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitrator liquidates in the Award the costs and fees of incidental proceedings. Where appropriate, the Center shall ask the Parties to settle the amount of such additional costs and fees..
        /// </summary>
        public static string Art7_1Provisions_L2 {
            get {
                return ResourceManager.GetString("Art7_1Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitrator may condemn one of the Parties to reimburse the other Party, in whole or in part, the arbitration costs and fees..
        /// </summary>
        public static string Art7_1Provisions_L3 {
            get {
                return ResourceManager.GetString("Art7_1Provisions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Furthermore, the Arbitrator may condemn one of the Parties to pay to the other Party the sum he determines in respect of the expenses incurred by this last and not included in the costs and fees of the arbitration..
        /// </summary>
        public static string Art7_1Provisions_L4 {
            get {
                return ResourceManager.GetString("Art7_1Provisions_L4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7.2.	Original Award in Electronic Format.
        /// </summary>
        public static string Art7_2 {
            get {
                return ResourceManager.GetString("Art7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Award is established by the Arbitrator in electronic format. It is dated and signed electronically by the Arbitrator. It is submitted by the Arbitrator to the Center and saved by the Center. The Center shall notify to the Parties the Award, signed electronically by the Arbitrator..
        /// </summary>
        public static string Art7_2Provisions {
            get {
                return ResourceManager.GetString("Art7_2Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7.3.	Execution of the Award.
        /// </summary>
        public static string Art7_3 {
            get {
                return ResourceManager.GetString("Art7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Provisional execution shall be attached to the Award unless the Arbitrator has provided otherwise..
        /// </summary>
        public static string Art7_3Provisions_L1 {
            get {
                return ResourceManager.GetString("Art7_3Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By agreeing to submit their Dispute to arbitration by the Center, the Parties commit to enforce the Award upon notification and waive any right to recourse to which they may validly waive, with the exception of an action to set aside..
        /// </summary>
        public static string Art7_3Provisions_L2 {
            get {
                return ResourceManager.GetString("Art7_3Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 7.4.	Exequatur.
        /// </summary>
        public static string Art7_4 {
            get {
                return ResourceManager.GetString("Art7_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At the request of a Party, the Center may mandate a lawyer, in the name and on behalf of this Party, to apply for exequatur and to entrust a bailiff with the enforcement of the Award..
        /// </summary>
        public static string Art7_4Provisions {
            get {
                return ResourceManager.GetString("Art7_4Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 8.	RECTIFICATIONS, FAILURE TO RULE AND INTERPRETATION.
        /// </summary>
        public static string Art8 {
            get {
                return ResourceManager.GetString("Art8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The arbitral tribunal may, at the request of one of the Parties, rectify clerical errors which would affect the Award..
        /// </summary>
        public static string Art8Provisions_L1 {
            get {
                return ResourceManager.GetString("Art8Provisions_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At the request of one of the Parties, the arbitral tribunal may supplement its Award if it has failed to rule on a claim it was mandated to decide upon or if he is required to interpret the Award..
        /// </summary>
        public static string Art8Provisions_L2 {
            get {
                return ResourceManager.GetString("Art8Provisions_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Requests for corrections of clerical errors and due to failures to rule or for the interpretation of the Award shall be sent by registered letter with acknowledgment of receipt to the Center, which shall refer the matter to the arbitral tribunal. The requests shall, however, be admissible only if the arbitral tribunal can be constituted again and if they are made less than three (3) months after the Award has been notified..
        /// </summary>
        public static string Art8Provisions_L3 {
            get {
                return ResourceManager.GetString("Art8Provisions_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If the arbitral tribunal cannot be constituted, this power shall vest in the court that has jurisdiction..
        /// </summary>
        public static string Art8Provisions_L4 {
            get {
                return ResourceManager.GetString("Art8Provisions_L4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The arbitral tribunal shall render its decision as soon as possible by reasoned decision..
        /// </summary>
        public static string Art8Provisions_L5 {
            get {
                return ResourceManager.GetString("Art8Provisions_L5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARTICLE 9.	ASSISTANCE AND REPRESENTATION OF THE  PARTIES.
        /// </summary>
        public static string Art9 {
            get {
                return ResourceManager.GetString("Art9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 9.1.	Assistance.
        /// </summary>
        public static string Art9_1 {
            get {
                return ResourceManager.GetString("Art9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Each Party may be assisted by a lawyer..
        /// </summary>
        public static string Art9_1Provisions {
            get {
                return ResourceManager.GetString("Art9_1Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 9.2.	Representation.
        /// </summary>
        public static string Art9_2 {
            get {
                return ResourceManager.GetString("Art9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Each Party may be represented during the arbitral proceedings by a lawyer mandated specifically to that effect..
        /// </summary>
        public static string Art9_2Provisions {
            get {
                return ResourceManager.GetString("Art9_2Provisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Award.
        /// </summary>
        public static string Award {
            get {
                return ResourceManager.GetString("Award", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à decision rendered by the Arbitrator so as to resolve the Dispute..
        /// </summary>
        public static string AwardDef {
            get {
                return ResourceManager.GetString("AwardDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à APPOINTMENT OF THE ARBITRAL TRIBUNAL.
        /// </summary>
        public static string BAppointment {
            get {
                return ResourceManager.GetString("BAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ARBITRAL PROCEEDINGS.
        /// </summary>
        public static string BArbProceedings {
            get {
                return ResourceManager.GetString("BArbProceedings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AWARD.
        /// </summary>
        public static string BAward {
            get {
                return ResourceManager.GetString("BAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CASE ESTABLISHMENT.
        /// </summary>
        public static string BCaseEstablishment {
            get {
                return ResourceManager.GetString("BCaseEstablishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CONFIDENTIALITY.
        /// </summary>
        public static string BConfidentiality {
            get {
                return ResourceManager.GetString("BConfidentiality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CORRECTION AND INTERPRETATION OF THE AWARD, OMISSION TO RULE.
        /// </summary>
        public static string BCorrection {
            get {
                return ResourceManager.GetString("BCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DEFINITIONS.
        /// </summary>
        public static string BDef {
            get {
                return ResourceManager.GetString("BDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FINAL PROVISIONS.
        /// </summary>
        public static string BFinalProvisions {
            get {
                return ResourceManager.GetString("BFinalProvisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IDENTIFICATIONS, NOTIFICATION AND COMMUNICATIONS.
        /// </summary>
        public static string BNotifications {
            get {
                return ResourceManager.GetString("BNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à REPRESENTATION AND ASSISTANCE.
        /// </summary>
        public static string BRepresentation {
            get {
                return ResourceManager.GetString("BRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SCOPE OF APPLICATION.
        /// </summary>
        public static string BScope {
            get {
                return ResourceManager.GetString("BScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SEIZING THE ARBITRAL TRIBUNAL.
        /// </summary>
        public static string BSeizingTrib {
            get {
                return ResourceManager.GetString("BSeizingTrib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TIME LIMITS.
        /// </summary>
        public static string BTimeLimits {
            get {
                return ResourceManager.GetString("BTimeLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Center.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Digital Institute of Arbitration and Mediation (Institut digital d’arbitrage et de médiation) acting as the administrator of the arbitration under article 1450 of the French Code of Civil Procedure..
        /// </summary>
        public static string CenterDef {
            get {
                return ResourceManager.GetString("CenterDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claimant.
        /// </summary>
        public static string Claimant {
            get {
                return ResourceManager.GetString("Claimant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Party having first brought its case to the Platform..
        /// </summary>
        public static string ClaimantDef {
            get {
                return ResourceManager.GetString("ClaimantDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Costs.
        /// </summary>
        public static string Costs {
            get {
                return ResourceManager.GetString("Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à contractual provisions determining the amount of costs and fees for the resolution of the Dispute via the Platform..
        /// </summary>
        public static string CostsDef {
            get {
                return ResourceManager.GetString("CostsDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Defendant.
        /// </summary>
        public static string Defendant {
            get {
                return ResourceManager.GetString("Defendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Party disputing the case brought by the Claimant..
        /// </summary>
        public static string DefendantDef {
            get {
                return ResourceManager.GetString("DefendantDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dispute.
        /// </summary>
        public static string Dispute {
            get {
                return ResourceManager.GetString("Dispute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à dispute between the Parties brought to arbitration before the Center..
        /// </summary>
        public static string DisputeDef {
            get {
                return ResourceManager.GetString("DisputeDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jurisdiction.
        /// </summary>
        public static string Jurisdiction {
            get {
                return ResourceManager.GetString("Jurisdiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à legal field within which the Center organizes the resolution of the Dispute..
        /// </summary>
        public static string JurisdictionDef {
            get {
                return ResourceManager.GetString("JurisdictionDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Party.
        /// </summary>
        public static string Party {
            get {
                return ResourceManager.GetString("Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claimant or Defendant..
        /// </summary>
        public static string PartyDef {
            get {
                return ResourceManager.GetString("PartyDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Platform.
        /// </summary>
        public static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à virtual space of Dispute resolution made available to Users by the Center and accessible at www.fast-arbitre.com, and sub-sites, mirror sites, portals and related URL variations..
        /// </summary>
        public static string PlatformDef {
            get {
                return ResourceManager.GetString("PlatformDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FastArbitre&apos;s Arbitration Rules.
        /// </summary>
        public static string RulesTitle {
            get {
                return ResourceManager.GetString("RulesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à any person logging in to the Platform for the resolution of a Dispute..
        /// </summary>
        public static string UserDef {
            get {
                return ResourceManager.GetString("UserDef", resourceCulture);
            }
        }
    }
}
