//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.WebPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClickNClaim.WebPortal.Resources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About FastArbitre.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accept the case.
        /// </summary>
        public static string AcceptCase {
            get {
                return ResourceManager.GetString("AcceptCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arbitration.
        /// </summary>
        public static string Arbitration {
            get {
                return ResourceManager.GetString("Arbitration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arbitration Center.
        /// </summary>
        public static string ArbitrationCenter {
            get {
                return ResourceManager.GetString("ArbitrationCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arbitration clause.
        /// </summary>
        public static string ArbitrationClause {
            get {
                return ResourceManager.GetString("ArbitrationClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arbitration request.
        /// </summary>
        public static string ArbitrationRequest {
            get {
                return ResourceManager.GetString("ArbitrationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you have not found an amicable agreement with the opposing party you can then apply for arbitration..
        /// </summary>
        public static string ArbitrationRequest1 {
            get {
                return ResourceManager.GetString("ArbitrationRequest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The center will take charge of your dispute and appoint an arbitrator in charge..
        /// </summary>
        public static string ArbitrationRequest2 {
            get {
                return ResourceManager.GetString("ArbitrationRequest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arbitrator.
        /// </summary>
        public static string Arbitrator {
            get {
                return ResourceManager.GetString("Arbitrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arbitre.
        /// </summary>
        public static string Arbitre {
            get {
                return ResourceManager.GetString("Arbitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Award.
        /// </summary>
        public static string Award {
            get {
                return ResourceManager.GetString("Award", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Before you begin, here is the procedure as it will unfold..
        /// </summary>
        public static string BeforeStarting {
            get {
                return ResourceManager.GetString("BeforeStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FastArbitre.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Case No.
        /// </summary>
        public static string CaseNo {
            get {
                return ResourceManager.GetString("CaseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à During your challenging of your opponent&apos;s declarations, we will first ask you to confirm the contact information that has been given to us about you, or to modify or add to it if necessary..
        /// </summary>
        public static string ChallengeInfo1 {
            get {
                return ResourceManager.GetString("ChallengeInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can then give your version of the facts by challenging your opponent&apos;s statement..
        /// </summary>
        public static string ChallengeInfo2 {
            get {
                return ResourceManager.GetString("ChallengeInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Once you have written your own statement, you will have the possibility to challenge each fact or document provided by the opposing party, as well as to add facts and document that you think are important to prove your point..
        /// </summary>
        public static string ChallengeInfo3 {
            get {
                return ResourceManager.GetString("ChallengeInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your challenge of the case finished, you will have the possibility to formulate your own claims..
        /// </summary>
        public static string ChallengeInfo4 {
            get {
                return ResourceManager.GetString("ChallengeInfo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finally, after having confirmed to us that you do or do not have an arbitration clause, your file will be finished and you will be able to review the summary of the case and your information..
        /// </summary>
        public static string ChallengeInfo5 {
            get {
                return ResourceManager.GetString("ChallengeInfo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One last thing left to do: find an amicable agreement for this dispute and end it, or formulate an arbitration request..
        /// </summary>
        public static string ChallengeInfo6 {
            get {
                return ResourceManager.GetString("ChallengeInfo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change situation.
        /// </summary>
        public static string ChangeSituation {
            get {
                return ResourceManager.GetString("ChangeSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à claim.
        /// </summary>
        public static string Claim {
            get {
                return ResourceManager.GetString("Claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claims.
        /// </summary>
        public static string Claims {
            get {
                return ResourceManager.GetString("Claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code of Ethics.
        /// </summary>
        public static string CodeOfEthics {
            get {
                return ResourceManager.GetString("CodeOfEthics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à © 2016 Copyright IDAM.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End of declaration.
        /// </summary>
        public static string EndOfDeclaration {
            get {
                return ResourceManager.GetString("EndOfDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while processing your request..
        /// </summary>
        public static string Error2 {
            get {
                return ResourceManager.GetString("Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Facts and Exhibits.
        /// </summary>
        public static string FactsExhibits {
            get {
                return ResourceManager.GetString("FactsExhibits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fast.
        /// </summary>
        public static string Fast {
            get {
                return ResourceManager.GetString("Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fields of expertise.
        /// </summary>
        public static string FieldsOfExpertise {
            get {
                return ResourceManager.GetString("FieldsOfExpertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File Administration.
        /// </summary>
        public static string FileAdministration {
            get {
                return ResourceManager.GetString("FileAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You will first enter your identification information and those of your opponent..
        /// </summary>
        public static string FirstID {
            get {
                return ResourceManager.GetString("FirstID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à has indicated.
        /// </summary>
        public static string HasIndicated {
            get {
                return ResourceManager.GetString("HasIndicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à How does it work?.
        /// </summary>
        public static string HowDoesItWork {
            get {
                return ResourceManager.GetString("HowDoesItWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identification.
        /// </summary>
        public static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impersonate.
        /// </summary>
        public static string Impersonate {
            get {
                return ResourceManager.GetString("Impersonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I understand!.
        /// </summary>
        public static string IUnderstand {
            get {
                return ResourceManager.GetString("IUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jobs.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You will also have the opportunity to declare a lawyer if you wish..
        /// </summary>
        public static string LawyerOptional {
            get {
                return ResourceManager.GetString("LawyerOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Legal Notices.
        /// </summary>
        public static string LegalNotices {
            get {
                return ResourceManager.GetString("LegalNotices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Locked out..
        /// </summary>
        public static string LockedOut1 {
            get {
                return ResourceManager.GetString("LockedOut1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This account has been locked out, please try again later..
        /// </summary>
        public static string LockedOut2 {
            get {
                return ResourceManager.GetString("LockedOut2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify Roles.
        /// </summary>
        public static string ModifyRole {
            get {
                return ResourceManager.GetString("ModifyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My cases.
        /// </summary>
        public static string MyCases {
            get {
                return ResourceManager.GetString("MyCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My claims.
        /// </summary>
        public static string MyClaims {
            get {
                return ResourceManager.GetString("MyClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My declaration.
        /// </summary>
        public static string MyDeclaration {
            get {
                return ResourceManager.GetString("MyDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No arbitrator nominated.
        /// </summary>
        public static string NoArbitrator {
            get {
                return ResourceManager.GetString("NoArbitrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No date saved.
        /// </summary>
        public static string NoDate {
            get {
                return ResourceManager.GetString("NoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No opposing party filled out.
        /// </summary>
        public static string NoOpposingParty {
            get {
                return ResourceManager.GetString("NoOpposingParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of case not indicated.
        /// </summary>
        public static string NoType {
            get {
                return ResourceManager.GetString("NoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Once your statement is complete, you can save it to come back to it later or send it to the opposing party..
        /// </summary>
        public static string OnceStatementFinished1 {
            get {
                return ResourceManager.GetString("OnceStatementFinished1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à He will be able to challenge your statement of claims on the platform. Then starts an exchange phase between you which can lead to an amicable agreement..
        /// </summary>
        public static string OnceStatementFinished2 {
            get {
                return ResourceManager.GetString("OnceStatementFinished2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This amicable phase is totally free, for yourself and the opposing party..
        /// </summary>
        public static string OnceStatementFinished3 {
            get {
                return ResourceManager.GetString("OnceStatementFinished3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At this stage, no arbitrator has been nominated and no costs have been incurred..
        /// </summary>
        public static string OnceStatementFinished4 {
            get {
                return ResourceManager.GetString("OnceStatementFinished4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à one event has been filled out.
        /// </summary>
        public static string OneEventFilledOut {
            get {
                return ResourceManager.GetString("OneEventFilledOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à open. You must end each of them to move on to the next step..
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open the free debate phase between the parties.
        /// </summary>
        public static string OpenFreeExchangePhase {
            get {
                return ResourceManager.GetString("OpenFreeExchangePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opposing party&apos;s statement.
        /// </summary>
        public static string OpposingPartiesStatement {
            get {
                return ResourceManager.GetString("OpposingPartiesStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pre-award.
        /// </summary>
        public static string PreAward {
            get {
                return ResourceManager.GetString("PreAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rates.
        /// </summary>
        public static string Rates {
            get {
                return ResourceManager.GetString("Rates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arbitration Rules.
        /// </summary>
        public static string RulesOfArbitration {
            get {
                return ResourceManager.GetString("RulesOfArbitration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Situation.
        /// </summary>
        public static string Situation {
            get {
                return ResourceManager.GetString("Situation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Then comes your statement. You will explain simply your dispute..
        /// </summary>
        public static string StatementInstructions1 {
            get {
                return ResourceManager.GetString("StatementInstructions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You will then detail the facts and upload the documents you find useful..
        /// </summary>
        public static string StatementInstructions2 {
            get {
                return ResourceManager.GetString("StatementInstructions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statement of Claims.
        /// </summary>
        public static string StatementOfClaims {
            get {
                return ResourceManager.GetString("StatementOfClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statements.
        /// </summary>
        public static string Statements {
            get {
                return ResourceManager.GetString("Statements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Steps.
        /// </summary>
        public static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Still.
        /// </summary>
        public static string Still {
            get {
                return ResourceManager.GetString("Still", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subscribe to our newsletter.
        /// </summary>
        public static string SubscribeToNewsletter {
            get {
                return ResourceManager.GetString("SubscribeToNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Summary of the case.
        /// </summary>
        public static string SummaryOfCase {
            get {
                return ResourceManager.GetString("SummaryOfCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your are at the moment on the summary page of the case..
        /// </summary>
        public static string SummaryPage1 {
            get {
                return ResourceManager.GetString("SummaryPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On this page you can find the information that.
        /// </summary>
        public static string SummaryPage2 {
            get {
                return ResourceManager.GetString("SummaryPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à has given us. You will first find the general summary of the case (number and parties)..
        /// </summary>
        public static string SummaryPage3 {
            get {
                return ResourceManager.GetString("SummaryPage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Below you will find each parties&apos; declarations, yours being still greyed while you have not gone on to the next stage..
        /// </summary>
        public static string SummaryPage4 {
            get {
                return ResourceManager.GetString("SummaryPage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à After your declarations, you will find a timeline of the facts and documents of the case. Reread carefully everything, this timeline is essential for a good understanding of the situation..
        /// </summary>
        public static string SummaryPage5 {
            get {
                return ResourceManager.GetString("SummaryPage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If you wish to respond to this case and potentially challenge parts of the statement, click on the button &quot;Challenge the declaration&quot;.
        /// </summary>
        public static string SummaryPage6 {
            get {
                return ResourceManager.GetString("SummaryPage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à at the top of the page..
        /// </summary>
        public static string SummaryPage7 {
            get {
                return ResourceManager.GetString("SummaryPage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technology and platform: Legal e-Services.
        /// </summary>
        public static string TechPltf {
            get {
                return ResourceManager.GetString("TechPltf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terms of Service.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transfer to the opposing party.
        /// </summary>
        public static string TransmissionToOpposingParty {
            get {
                return ResourceManager.GetString("TransmissionToOpposingParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Administration.
        /// </summary>
        public static string UserAdministration {
            get {
                return ResourceManager.GetString("UserAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to FastArbitre..
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à has declared a dispute on our FastArbitre platform. This person has asked us to inform you of his declaration. At this stage it is a purely amicable phase, free and confidential. No arbitrator has been nominated..
        /// </summary>
        public static string Welcome1 {
            get {
                return ResourceManager.GetString("Welcome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à wishes to resolve this dispute amicably. FastArbitre has allowed him to detail it..
        /// </summary>
        public static string Welcome2 {
            get {
                return ResourceManager.GetString("Welcome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We will now quickly show you what will follow..
        /// </summary>
        public static string Welcome3 {
            get {
                return ResourceManager.GetString("Welcome3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à events have been filled out.
        /// </summary>
        public static string XEventsFilledOut {
            get {
                return ResourceManager.GetString("XEventsFilledOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your challenge.
        /// </summary>
        public static string YourChallenge {
            get {
                return ResourceManager.GetString("YourChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your claims.
        /// </summary>
        public static string YourClaims {
            get {
                return ResourceManager.GetString("YourClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finally, you will indicate what you expect from your opponent..
        /// </summary>
        public static string YourClaimsInstructions1 {
            get {
                return ResourceManager.GetString("YourClaimsInstructions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You will fill in as many requests as you want and justify them all..
        /// </summary>
        public static string YourClaimsInstructions2 {
            get {
                return ResourceManager.GetString("YourClaimsInstructions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your declaration.
        /// </summary>
        public static string YourDeclaration {
            get {
                return ResourceManager.GetString("YourDeclaration", resourceCulture);
            }
        }
    }
}
