//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.WebPortal.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Viewer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Viewer() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClickNClaim.WebPortal.Resources.Viewer", typeof(Viewer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access the video conference.
        /// </summary>
        public static string AccessVideoConf {
            get {
                return ResourceManager.GetString("AccessVideoConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add another date.
        /// </summary>
        public static string AddOtherDate {
            get {
                return ResourceManager.GetString("AddOtherDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Address 1.
        /// </summary>
        public static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Address 2.
        /// </summary>
        public static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Address 3.
        /// </summary>
        public static string Address3 {
            get {
                return ResourceManager.GetString("Address3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A document linked to this event.
        /// </summary>
        public static string ADocumentLinked {
            get {
                return ResourceManager.GetString("ADocumentLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arbitration Request.
        /// </summary>
        public static string ArbitrationRequest {
            get {
                return ResourceManager.GetString("ArbitrationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are about to submit a request for arbitration. This request binds you: it constitutes the first act of the arbitration procedure..
        /// </summary>
        public static string ArbitrationRequestWarning1 {
            get {
                return ResourceManager.GetString("ArbitrationRequestWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are about to submit a request for arbitration. The arbitration procedure will be initiated when your opponent accepts this request..
        /// </summary>
        public static string ArbitrationRequestWarning2 {
            get {
                return ResourceManager.GetString("ArbitrationRequestWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your opponent has requested an arbitration. Please fill in your official information and pay your half of the fees..
        /// </summary>
        public static string ArbitrationRequestWarning3 {
            get {
                return ResourceManager.GetString("ArbitrationRequestWarning3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Award.
        /// </summary>
        public static string Award {
            get {
                return ResourceManager.GetString("Award", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Case Situation.
        /// </summary>
        public static string CaseSituation {
            get {
                return ResourceManager.GetString("CaseSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Challenge by.
        /// </summary>
        public static string ChallengeBy {
            get {
                return ResourceManager.GetString("ChallengeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Challenge the declaration made by.
        /// </summary>
        public static string ChallengeDeclaration {
            get {
                return ResourceManager.GetString("ChallengeDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Challenge the document.
        /// </summary>
        public static string ChallengeDocument {
            get {
                return ResourceManager.GetString("ChallengeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claim.
        /// </summary>
        public static string Claim {
            get {
                return ResourceManager.GetString("Claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your Company&apos;s Official Information.
        /// </summary>
        public static string CompanyID {
            get {
                return ResourceManager.GetString("CompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Company&apos;s registration number.
        /// </summary>
        public static string CompanyRegistrationNo {
            get {
                return ResourceManager.GetString("CompanyRegistrationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Company&apos;s form (unlimited liability, limited liability, etc).
        /// </summary>
        public static string CompanysForm {
            get {
                return ResourceManager.GetString("CompanysForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Company&apos;s phone number.
        /// </summary>
        public static string CompanysPhone {
            get {
                return ResourceManager.GetString("CompanysPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm and pay.
        /// </summary>
        public static string ConfirmAndPay {
            get {
                return ResourceManager.GetString("ConfirmAndPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The confirmation of your application and your access codes to the arbitration procedure will be sent to the legal representative of your organization by registered mail, to the address of the head office of your company. Please check these items. The access codes for the arbitration phase will be sent to you in this registered letter..
        /// </summary>
        public static string ConfirmationAndAccessCodes {
            get {
                return ResourceManager.GetString("ConfirmationAndAccessCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation and Payment.
        /// </summary>
        public static string ConfirmationAndPayment {
            get {
                return ResourceManager.GetString("ConfirmationAndPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact the arbitrator.
        /// </summary>
        public static string ContactTheArbitrator {
            get {
                return ResourceManager.GetString("ContactTheArbitrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Corporate name.
        /// </summary>
        public static string CorporateName {
            get {
                return ResourceManager.GetString("CorporateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 750€ excluding tax.
        /// </summary>
        public static string Cost1 {
            get {
                return ResourceManager.GetString("Cost1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1250€ excluding tax.
        /// </summary>
        public static string Cost2 {
            get {
                return ResourceManager.GetString("Cost2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1750€ excluding tax.
        /// </summary>
        public static string Cost3 {
            get {
                return ResourceManager.GetString("Cost3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2250€ excluding tax.
        /// </summary>
        public static string Cost4 {
            get {
                return ResourceManager.GetString("Cost4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The resolution of your dispute by FastArbitre arbitration will cost.
        /// </summary>
        public static string CostOfArbitration1 {
            get {
                return ResourceManager.GetString("CostOfArbitration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à per party..
        /// </summary>
        public static string CostOfArbitration2 {
            get {
                return ResourceManager.GetString("CostOfArbitration2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Counsel of.
        /// </summary>
        public static string CounselOf {
            get {
                return ResourceManager.GetString("CounselOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date and time of the videoconference.
        /// </summary>
        public static string DateAndTimeVideoConf {
            get {
                return ResourceManager.GetString("DateAndTimeVideoConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The date of the event.
        /// </summary>
        public static string DateOfEvent {
            get {
                return ResourceManager.GetString("DateOfEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please indicate the days on which you would be free for the videoconference.
        /// </summary>
        public static string DatesVideoConf {
            get {
                return ResourceManager.GetString("DatesVideoConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Declaration by.
        /// </summary>
        public static string DeclarationBy {
            get {
                return ResourceManager.GetString("DeclarationBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description (optional).
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description of the proceedings.
        /// </summary>
        public static string DescriptionIncidentalProceedings {
            get {
                return ResourceManager.GetString("DescriptionIncidentalProceedings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description of the challenge.
        /// </summary>
        public static string DescriptionOfChallenge {
            get {
                return ResourceManager.GetString("DescriptionOfChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description of the discussion.
        /// </summary>
        public static string DescriptionOfDiscussion {
            get {
                return ResourceManager.GetString("DescriptionOfDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detail the reason of your disagreement on this event.
        /// </summary>
        public static string DetailReasonOfDisagreement {
            get {
                return ResourceManager.GetString("DetailReasonOfDisagreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disagreement on the event.
        /// </summary>
        public static string DisagreementOnEvent {
            get {
                return ResourceManager.GetString("DisagreementOnEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disagreement(s) with.
        /// </summary>
        public static string DisagreementWith {
            get {
                return ResourceManager.GetString("DisagreementWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à disagrees.
        /// </summary>
        public static string Disagrees {
            get {
                return ResourceManager.GetString("Disagrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your request for arbitration has been sent to your opponent. The arbitration procedure will start as soon as he has accepted it..
        /// </summary>
        public static string DisputeSentToAdversary {
            get {
                return ResourceManager.GetString("DisputeSentToAdversary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your dispute has just been submitted to FastArbitre for validation. We will come back to you very soon..
        /// </summary>
        public static string DisputeSubmitted {
            get {
                return ResourceManager.GetString("DisputeSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dispute Timeline.
        /// </summary>
        public static string DisputeTimeline {
            get {
                return ResourceManager.GetString("DisputeTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download and sign electronically the document.
        /// </summary>
        public static string DownloadAndSign {
            get {
                return ResourceManager.GetString("DownloadAndSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duration of the stage (in days).
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duration of the proceedings (in days).
        /// </summary>
        public static string DurationIncidentalProceedings {
            get {
                return ResourceManager.GetString("DurationIncidentalProceedings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duration of the discussion (in days).
        /// </summary>
        public static string DurationOfDiscussion {
            get {
                return ResourceManager.GetString("DurationOfDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please estimate the duration of the videoconference.
        /// </summary>
        public static string DurationVideoConf {
            get {
                return ResourceManager.GetString("DurationVideoConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email for.
        /// </summary>
        public static string EmailFor {
            get {
                return ResourceManager.GetString("EmailFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email for the arbitrator.
        /// </summary>
        public static string EmailForArbitrator {
            get {
                return ResourceManager.GetString("EmailForArbitrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End of Stage.
        /// </summary>
        public static string EndOfStage {
            get {
                return ResourceManager.GetString("EndOfStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The event and its description.
        /// </summary>
        public static string EventAndDescription {
            get {
                return ResourceManager.GetString("EventAndDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The event itself.
        /// </summary>
        public static string EventItself {
            get {
                return ResourceManager.GetString("EventItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please explain why you are refusing this videoconference.
        /// </summary>
        public static string ExplainVideoConfRefusal {
            get {
                return ResourceManager.GetString("ExplainVideoConfRefusal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please indicate a reason for organizing this videoconference.
        /// </summary>
        public static string GiveReasonForVideoConf {
            get {
                return ResourceManager.GetString("GiveReasonForVideoConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Has yet to fill out a challenge.
        /// </summary>
        public static string HasYetToFillOutChallenge {
            get {
                return ResourceManager.GetString("HasYetToFillOutChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à has yet to fill out a declaration.
        /// </summary>
        public static string HasYetToFillOutDeclaration {
            get {
                return ResourceManager.GetString("HasYetToFillOutDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I disagree with.
        /// </summary>
        public static string IDisagreeWith {
            get {
                return ResourceManager.GetString("IDisagreeWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specify the date on which you think this event took place.
        /// </summary>
        public static string IndicateDateYouBelieve {
            get {
                return ResourceManager.GetString("IndicateDateYouBelieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indicate the document on which you disagree.
        /// </summary>
        public static string IndicateDocument {
            get {
                return ResourceManager.GetString("IndicateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initiate a debate.
        /// </summary>
        public static string InitiateADiscussion {
            get {
                return ResourceManager.GetString("InitiateADiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initiate a debate between the parties.
        /// </summary>
        public static string InitiateDiscussion {
            get {
                return ResourceManager.GetString("InitiateDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initiate the debate.
        /// </summary>
        public static string InitiateDiscussion2 {
            get {
                return ResourceManager.GetString("InitiateDiscussion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initiate incidental proceedings.
        /// </summary>
        public static string InitiateIncidentalProceedings {
            get {
                return ResourceManager.GetString("InitiateIncidentalProceedings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initiate the proceedings.
        /// </summary>
        public static string InitiateProceedings {
            get {
                return ResourceManager.GetString("InitiateProceedings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à in progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message for.
        /// </summary>
        public static string MessageFor {
            get {
                return ResourceManager.GetString("MessageFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of the event.
        /// </summary>
        public static string NameOfEntry {
            get {
                return ResourceManager.GetString("NameOfEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please name this videoconference.
        /// </summary>
        public static string NameVideoConf {
            get {
                return ResourceManager.GetString("NameVideoConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New event.
        /// </summary>
        public static string NewEntry {
            get {
                return ResourceManager.GetString("NewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No counsel.
        /// </summary>
        public static string NoCounsel {
            get {
                return ResourceManager.GetString("NoCounsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No declaration has been filled out for the moment..
        /// </summary>
        public static string NoDeclarationFilledOut {
            get {
                return ResourceManager.GetString("NoDeclarationFilledOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à For the moment there is no entry for this dispute..
        /// </summary>
        public static string NoEntryExistsForDispute {
            get {
                return ResourceManager.GetString("NoEntryExistsForDispute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No debates in progress.
        /// </summary>
        public static string NoExchanges {
            get {
                return ResourceManager.GetString("NoExchanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No price offer exists for your dispute. It will be transferred to FastArbitre&apos;s board so that the type of dispute you are submitting can be determined and so that a quotation may be sent back to you within 72h..
        /// </summary>
        public static string NoQuotation {
            get {
                return ResourceManager.GetString("NoQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no video conference scheduled.
        /// </summary>
        public static string NoVideoConfScheduled {
            get {
                return ResourceManager.GetString("NoVideoConfScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Object of the challenge.
        /// </summary>
        public static string ObjectOfChallenge {
            get {
                return ResourceManager.GetString("ObjectOfChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Object of the debate.
        /// </summary>
        public static string ObjectOfDiscussion {
            get {
                return ResourceManager.GetString("ObjectOfDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Object of the proceedings.
        /// </summary>
        public static string ObjectOfProceedings {
            get {
                return ResourceManager.GetString("ObjectOfProceedings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Organization of the video conference in progress.
        /// </summary>
        public static string OrganisationOfVideoConf {
            get {
                return ResourceManager.GetString("OrganisationOfVideoConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Organize a videoconference.
        /// </summary>
        public static string OrganizeVideoConf {
            get {
                return ResourceManager.GetString("OrganizeVideoConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The parties to the dispute.
        /// </summary>
        public static string PartiesToTheDispute {
            get {
                return ResourceManager.GetString("PartiesToTheDispute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment made.
        /// </summary>
        public static string PaymentMade {
            get {
                return ResourceManager.GetString("PaymentMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plan a videoconference.
        /// </summary>
        public static string PlanVideoConf {
            get {
                return ResourceManager.GetString("PlanVideoConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please name this event.
        /// </summary>
        public static string PleaseNameEntry {
            get {
                return ResourceManager.GetString("PleaseNameEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Postal code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pre-award.
        /// </summary>
        public static string PreAward {
            get {
                return ResourceManager.GetString("PreAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Public registry report.
        /// </summary>
        public static string PublicRegistryReport {
            get {
                return ResourceManager.GetString("PublicRegistryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reason for refusing.
        /// </summary>
        public static string ReasonForRefusing {
            get {
                return ResourceManager.GetString("ReasonForRefusing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The reason for which you would like a videoconference to take place.
        /// </summary>
        public static string ReasonForVideoConf {
            get {
                return ResourceManager.GetString("ReasonForVideoConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Request an arbitration.
        /// </summary>
        public static string RequestArbitration {
            get {
                return ResourceManager.GetString("RequestArbitration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à said.
        /// </summary>
        public static string Said {
            get {
                return ResourceManager.GetString("Said", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hic quasi placeat iure tempora laudantium ipsa ad debitis unde? Iste voluptatibus minus veritatis qui ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto, optio, dolorum provident rerum aut hi [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Section1Content {
            get {
                return ResourceManager.GetString("Section1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title of section 1.
        /// </summary>
        public static string Section1Title {
            get {
                return ResourceManager.GetString("Section1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à See the discussion.
        /// </summary>
        public static string SeeDiscussion {
            get {
                return ResourceManager.GetString("SeeDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View summary of my dispute.
        /// </summary>
        public static string SeeDisputeSummary {
            get {
                return ResourceManager.GetString("SeeDisputeSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à See videoconference.
        /// </summary>
        public static string SeeVideoConf {
            get {
                return ResourceManager.GetString("SeeVideoConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Share capital.
        /// </summary>
        public static string ShareCapital {
            get {
                return ResourceManager.GetString("ShareCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This step requires that you set a number of days after which the dispute will automatically move on to the next step..
        /// </summary>
        public static string StepRequirementsDays {
            get {
                return ResourceManager.GetString("StepRequirementsDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suggest these dates.
        /// </summary>
        public static string SuggestDates {
            get {
                return ResourceManager.GetString("SuggestDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Summary of the case.
        /// </summary>
        public static string SummaryOfCase {
            get {
                return ResourceManager.GetString("SummaryOfCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Arbitrator.
        /// </summary>
        public static string TheArbitrator {
            get {
                return ResourceManager.GetString("TheArbitrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The exhibit(s).
        /// </summary>
        public static string TheExhibit {
            get {
                return ResourceManager.GetString("TheExhibit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Their companies.
        /// </summary>
        public static string TheirCompanies {
            get {
                return ResourceManager.GetString("TheirCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Their counsel.
        /// </summary>
        public static string TheirCounsel {
            get {
                return ResourceManager.GetString("TheirCounsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Siren (*).
        /// </summary>
        public static string UniqueIDNo {
            get {
                return ResourceManager.GetString("UniqueIDNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown address.
        /// </summary>
        public static string UnknownAddress {
            get {
                return ResourceManager.GetString("UnknownAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown corporate name.
        /// </summary>
        public static string UnknownCorporateName {
            get {
                return ResourceManager.GetString("UnknownCorporateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown SIREN.
        /// </summary>
        public static string UnknownUniqueID {
            get {
                return ResourceManager.GetString("UnknownUniqueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update companies&apos; information.
        /// </summary>
        public static string UpdateCompaniesInfo {
            get {
                return ResourceManager.GetString("UpdateCompaniesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upload the electronically signed document.
        /// </summary>
        public static string UpdloadSignedDoc {
            get {
                return ResourceManager.GetString("UpdloadSignedDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Video conference scheduled on.
        /// </summary>
        public static string VideoConfDate {
            get {
                return ResourceManager.GetString("VideoConfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Link to the videoconference.
        /// </summary>
        public static string VideoConfLink {
            get {
                return ResourceManager.GetString("VideoConfLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Videoconference refusal.
        /// </summary>
        public static string VideoConfRefusal {
            get {
                return ResourceManager.GetString("VideoConfRefusal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View messages.
        /// </summary>
        public static string ViewMessages {
            get {
                return ResourceManager.GetString("ViewMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can contact the arbitrator at any time. A copy of your message will be automatically sent to the other party..
        /// </summary>
        public static string YouCanContactArbitrator {
            get {
                return ResourceManager.GetString("YouCanContactArbitrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can contact either of the parties at any time. A copy of your message will be automatically sent to the other party..
        /// </summary>
        public static string YouCanContactParty {
            get {
                return ResourceManager.GetString("YouCanContactParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You would like to go on to the next step with this dispute.
        /// </summary>
        public static string YouWantNextStep {
            get {
                return ResourceManager.GetString("YouWantNextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You would like for the arbitrator to organize a videoconference. Please give a  reason. The arbitrator may accept or refuse your request. If the arbitrator agrees, he will suggest a series of dates for the videoconference to be scheduled..
        /// </summary>
        public static string YouWantVideoConf {
            get {
                return ResourceManager.GetString("YouWantVideoConf", resourceCulture);
            }
        }
    }
}
