//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string IdUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int IdEvent { get; set; }
        public string UserEmail { get; set; }
    
        public virtual AspNetUser CreatedBy { get; set; }
        public virtual Event Event { get; set; }
    }
}
