//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConflictStateHistoric
    {
        public int Id { get; set; }
        public int ConflictStateId { get; set; }
        public string ConflictStateName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> CountDown { get; set; }
        public int IdConflict { get; set; }
    
        public virtual Conflict Conflict { get; set; }
    }
}
