//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conflict
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conflict()
        {
            this.ProofFiles = new HashSet<ProofFile>();
            this.UsersInConflicts = new HashSet<UsersInConflict>();
            this.Resolutions = new HashSet<Resolution>();
            this.Invitations = new HashSet<Invitation>();
            this.Events = new HashSet<Event>();
            this.ConflictLegalDocuments = new HashSet<LegalDocument>();
            this.MeetingDebates = new HashSet<MeetingDebate>();
            this.ConflictStateHistorics = new HashSet<ConflictStateHistoric>();
            this.Messages = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdConflictType { get; set; }
        public string IdCreationUser { get; set; }
        public int State { get; set; }
        public bool HasArbitralClause { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string IdArbiterAssigned { get; set; }
        public Nullable<bool> HasArbiterAccepted { get; set; }
        public Nullable<bool> ArbiterRecognizeNoConflictOfInterest { get; set; }
        public Nullable<bool> ArbiterRecognizeLegitimate { get; set; }
        public string ArbiterPreConclusion { get; set; }
        public string ArbiterConclusion { get; set; }
        public Nullable<bool> AskedForArbitration { get; set; }
        public Nullable<int> PaymentState { get; set; }
    
        public virtual AspNetUser CreatedBy { get; set; }
        public virtual ConflictType ConflictType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProofFile> ProofFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersInConflict> UsersInConflicts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resolution> Resolutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invitation> Invitations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        public virtual AspNetUser Arbiter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegalDocument> ConflictLegalDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingDebate> MeetingDebates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConflictStateHistoric> ConflictStateHistorics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
    }
}
