//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConflictType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConflictType()
        {
            this.Conflicts = new HashSet<Conflict>();
            this.DefaultEvents = new HashSet<DefaultEvent>();
            this.ResolutionTypes = new HashSet<ResolutionType>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsMapped { get; set; }
        public string Code { get; set; }
        public string Info { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conflict> Conflicts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefaultEvent> DefaultEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResolutionType> ResolutionTypes { get; set; }
    }
}
