//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Debate()
        {
            this.MailDebates = new HashSet<MailDebate>();
        }
    
        public int Id { get; set; }
        public int Type { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int IdEvent { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Closed { get; set; }
        public Nullable<int> CountDown { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailDebate> MailDebates { get; set; }
        public virtual Event Event { get; set; }
    }
}
