//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultEvent
    {
        public int Id { get; set; }
        public int IdConflictType { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public string Placeholder { get; set; }
        public int Type { get; set; }
        public string SubAccordTitle { get; set; }
        public string SubAccordInfo { get; set; }
        public string SubAccordPlaceholder { get; set; }
        public string SubPbTitle { get; set; }
        public string SubPbInfo { get; set; }
        public string SubPbPlaceholder { get; set; }
    
        public virtual ConflictType ConflictType { get; set; }
    }
}
