//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disagreement
    {
        public int Id { get; set; }
        public int IdEvent { get; set; }
        public string IdUser { get; set; }
        public bool DisagreementOnDescription { get; set; }
        public bool DisagreementOnDate { get; set; }
        public bool DisagreementOnPiece { get; set; }
        public Nullable<System.DateTime> ConcurrentDate { get; set; }
        public string ConcurrentDescription { get; set; }
        public string ConcurrentPieces { get; set; }
        public string Comment { get; set; }
        public bool IsResolved { get; set; }
    
        public virtual AspNetUser CreatedBy { get; set; }
        public virtual Event Event { get; set; }
    }
}
