//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitation
    {
        public System.Guid Id { get; set; }
        public int IdConflict { get; set; }
        public string Email { get; set; }
        public bool IsUsed { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public string IdLawyer { get; set; }
        public bool IsLawyer { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
    
        public virtual Conflict Conflict { get; set; }
        public virtual AspNetUser Lawyer { get; set; }
    }
}
