//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailDebate
    {
        public int Id { get; set; }
        public int IdDebate { get; set; }
        public string Body { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> IdFile { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Debate Debate { get; set; }
        public virtual ProofFile ProofFile { get; set; }
    }
}
