//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingPropositionAnswer
    {
        public int Id { get; set; }
        public int IdMeetingProposition { get; set; }
        public string IdUser { get; set; }
        public bool Response { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual MeetingProposition MeetingProposition { get; set; }
    }
}
