//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingProposition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeetingProposition()
        {
            this.MeetingPropositionAnswers = new HashSet<MeetingPropositionAnswer>();
        }
    
        public int Id { get; set; }
        public int IdMeetingDebate { get; set; }
        public System.DateTime DateTimeProposition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingPropositionAnswer> MeetingPropositionAnswers { get; set; }
        public virtual MeetingDebate MeetingDebate { get; set; }
    }
}
