//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingDebate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeetingDebate()
        {
            this.MeetingPropositions = new HashSet<MeetingProposition>();
        }
    
        public int Id { get; set; }
        public int IdConflict { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Link { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string EstimateDuration { get; set; }
        public int IdEvent { get; set; }
    
        public virtual Conflict Conflict { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingProposition> MeetingPropositions { get; set; }
        public virtual Event Event { get; set; }
    }
}
