//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resolution
    {
        public int Id { get; set; }
        public string ResolutionValue { get; set; }
        public string ResolutionComment { get; set; }
        public string IdUser { get; set; }
        public int IdConflict { get; set; }
        public int IdResolutionType { get; set; }
        public Nullable<int> IdEvent { get; set; }
    
        public virtual AspNetUser User { get; set; }
        public virtual Conflict Conflict { get; set; }
        public virtual ResolutionType ResolutionType { get; set; }
        public virtual Event Event { get; set; }
    }
}
