//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickNClaim.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInConflict
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersInConflict()
        {
            this.IsPhysical = true;
            this.IsRepresented = false;
        }
    
        public int IdConflict { get; set; }
        public string IdUser { get; set; }
        public string UserDescriptionOfTheConflict { get; set; }
        public string CompanyName { get; set; }
        public string UserFunction { get; set; }
        public Nullable<bool> IsLegalRepresentative { get; set; }
        public Nullable<bool> ReadyForArbitration { get; set; }
        public bool IsPhysical { get; set; }
        public bool IsRepresented { get; set; }
        public Nullable<bool> IsLawyer { get; set; }
        public string IdLawyer { get; set; }
        public Nullable<bool> HasAcceptedArbitration { get; set; }
        public bool Disable { get; set; }
        public bool Completed { get; set; }
        public Nullable<int> IdUserCompany { get; set; }
        public string Siret { get; set; }
    
        public virtual AspNetUser User { get; set; }
        public virtual Conflict Conflict { get; set; }
        public virtual AspNetUser Lawyer { get; set; }
        public virtual UserCompany UserCompany { get; set; }
    }
}
